### ISSUE TITLE
Add context cancellation to backup routines

### ISSUE THREAD

**Issue by nilslice** [ponzu-cms/ponzu#110]
When backing up components of a Ponzu system via HTTP backup utility, we should provide a cancellation context so dropped connections will stop the backup. Some backups can be very expensive, especially the tar/gzip archiving of uploads. 

https://github.com/ponzu-cms/ponzu/blob/3a897e4db97cc6f5e47f395662499402eb4c2bda/system/admin/handlers.go#L192

each `Backup` func will need to take the `req` with the context added with cancellation propagation.

**Comment by eticzon** [comment]
Hi @nilslice! Would you mind if I have crack at this? I want to trial `ponzu` as a CMS for personal projects. What better way to learn that to dive right in the codebase! 😄

**Comment by nilslice** [comment]
Hey @eticzon - please do! Thank you & let me know if you have any questions.

**Comment by nilslice** [comment]
Hi @eticzon - checking in with you on the status of this in case you had made some progress or needed help? I'll hopefully have some time this weekend for issue clean-up and this PR is on my list to get done sooner than later.

**Comment by eticzon** [comment]
Hey @nilslice! Apologies for the delay. Yup, just familiarising myself with the overall project structure and all but I should be able to create a PR before the weekend.

**Comment by nilslice** [comment]
Awesome. I didn't mean any rush, just figured I'd ask and avoid duplicating efforts. Thank you!
