### ISSUE TITLE
Non admin users

### ISSUE THREAD

**Issue by RPallas92** [ponzu-cms/ponzu#112]
Is it possible to add non-admin users that only can edit the content and can't change the system settings? 

Thanks in advance

**Comment by nilslice** [comment]
Hi @RPallas92 -

Not currently, no. I would certainly consider this as it is a feature which would make Ponzu more of a competitive CMS, but it isn't on my immediate roadmap. However, I would gladly accept a PR for it :)

**Comment by nilslice** [comment]
@RPallas92 - I am going to add this to the Community Suggested Features project and keep you tagged so if someone decides to work on this you'll be notified. If you decide you'd like to give it a shot, let me know and I'll adjust the project status and offer any help I can to get you started. Closing this for now, but adding the deferred tag so it doesn't get lost!

**Comment by rebootcode** [comment]
Given the option - there is API method on how to create content and update content - https://docs.ponzu-cms.org/HTTP-APIs/Content/#new-content 

You can create and set various role externally.
