### ISSUE TITLE
ponzu does not handle underscores in the variable names very well

### ISSUE THREAD

**Issue by devdavidkarlsson** [ponzu-cms/ponzu#113]
`{
data: [
{
uuid: "574cb970-2863-4e7a-b9da-a440987dc55e",
id: 1,
slug: "item-id-574cb970-2863-4e7a-b9da-a440987dc55e",
timestamp: 1491778146000,
updated: 1491821466260,
c_o_n_f_i_r_m_h_e_a_d_i_n_g_p_a_p_e_r_s_i_g_n_i_n_g: "lalalal",
c_o_n_f_i_r_m_b_o_d_y_p_a_p_e_r_s_i_g_n_i_n_g: "",

Why all the underscores in the repsonse from the API?

When creating a content with: `CONFIRM_HEADING_PAPER_SIGNING:"string"` this is what gets shown in the UI: CONFIRMHEADINGPAPERSIGNING. and the JSON response is shown above... 

Ludacris underscorestrings.... why....

**Comment by nilslice** [comment]
Hi @devdavidkalrsson -

In an attempt to make the type and field name parser adhere to common Go idioms, the character after a capital letter is separated by an underscore in the JSON tag name. For example:

FieldName -> field_name 
and inversely,
field_name -> FieldName

In the Ponzu generator, you should type in these names as they would appear in your code. It's very uncommon in Go to use a field name like the one you provided.

**Comment by devdavidkarlsson** [comment]
Thanks for clarifying...
