### ISSUE TITLE
Need to add following links to repo.

### ISSUE THREAD

**Issue by ashishmohite** [ponzu-cms/ponzu#118]
godoc.org:
goreportcard.com:
coverage service link (gocover, coveralls etc.):

**Comment by nilslice** [comment]
Thank you @ashishmohite - lots of details to add! 

Would you be interested in helping set some of these up? You will notice we are very light on tests, any help there would also be very helpful.

Did you get a chance to try Ponzu?

**Comment by nilslice** [comment]
Added godoc & report card for now. Once we are closer to 1.0 and have testing suite complete, I will include the coverage one.

Thanks!
