### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Riari** [ponzu-cms/ponzu#128]
Hi,

Nice work on this CMS, it's very nice. There's just one obstacle I haven't been able to work around: the lack of ability to display snippets of code in a richtext field. I tried using highlight.js in my frontend, with the standard `<pre><code>...</code></pre>` syntax in my `body` field, but the editor strips it out.

Beyond changing the field to a plain textarea for now, any other suggestions? Could this be considered for a potential feature?

Thanks

**Comment by nilslice** [comment]
Hi @Riari -

Thank you for the kind words. I'm glad you think so!

Just to clarify.. you are using a `editor.Richtext()` in your content type's `MarshalEditor()` to create the editor within the CMS. When you type `<pre><code>...</code></pre>` inside the richtext editor, those pre/code blocks are deleted from your input entirely?

Assuming the above is accurate, are the pre/code blocks stripped out after you hit 'Save'? Or, are you writing your pre/code blocks inside the "code view" (the `<>` icon in the richtext editor) or in the "standard view"? 

Is the content inside the pre/code block stripped as well, or only the pre/code HTML tags?

Steve

**Comment by nilslice** [comment]
>Beyond changing the field to a plain textarea for now, any other suggestions? Could this be considered for a potential feature?

I think if we don't find a solution to your issue, adding a `editor.Code()` func that simplifies writing formatted and syntax highlighted code would be a great feature to consider.

**Comment by Riari** [comment]
I was entering the pre/code markup in the code view and hitting Save immediately after that. After testing further, it appears that _anything_ you enter in that view gets lost on save unless you switch back to the preview first (I guess the editor doesn't commit changes to the textarea until that point). So that's another issue altogether.

While that does mean it's possible to use the markup with `editor.Richtext()`, it presents another issue: when you change back to the preview, the markup is automatically formatted and that's problematic for `pre` elements since there's extra whitespace resulting from the indentation.

Having a `editor.Code()` sounds good, but I don't know how suitable it would be for my particular use case (basically blog posts with code samples featured throughout).

Hope that helps :) I'm somewhat new to Go myself, otherwise I'd offer to explore a potential PR for this.

**Comment by nilslice** [comment]
@Riari - would a markdown editor with syntax highlighting work, i.e. https://jbt.github.io/markdown-editor ?

**Comment by Riari** [comment]
Yeah, something like that would be ideal actually.

**Comment by nilslice** [comment]
Yea, I think it could be a nice addition too. Would you prefer the un-rendered markdown, or rendered html in the json api responses?

**Comment by Riari** [comment]
Having the HTML returned would suit me, but having the option to control it might be nice - maybe through an option in the admin config, or a checkbox below the editor in the form, or a querystring param like `?renderMarkdown=1`.

**Comment by nilslice** [comment]
Ok, thanks for the feedback. Would it be a significant issue if we were to only return the raw markdown? or would client-side markdown parsing be something you can live with?

**Comment by Riari** [comment]
That would be fine, actually :) I have no issue rendering client-side.

**Comment by nilslice** [comment]
Hey - sorry for the long delay, I have had a bunch of "day job" work eating up most of my time... I found someone had made a markdown editor input for Ponzu.. maybe this would work for you? 

https://github.com/aleksen/smdeditor cc: @aleksen

since there is no license, you should be careful what you're using it for.. maybe the author will consider adding one (I suggest BSD like ponzu or MIT if you like it better)

**Comment by Riari** [comment]
Thanks for the heads up; I'll take a look. If nothing else, at least it'll give me an idea of how to tackle it.

**Comment by aleksen** [comment]
Hi! I haven't put a licence in there yet, but it will be BSD. Feel free to fork or create PRs for the plugin.

**Comment by nilslice** [comment]
@aleksen - I may need it for a upcoming project and if I do, I'd be happy to contribute to your repo.

**Comment by olliephillips** [comment]
Closing this issue. It's been a while since there has been any activity. Please reopen if need to.
