### ISSUE TITLE
Help on deploy

### ISSUE THREAD

**Issue by jksmithiii** [ponzu-cms/ponzu#130]
I rent a vm on GAE to host windows exes. So far, while my ponzu exe works on localhost in the vm, I can't get a public ip to show anything, even with the firewall turned off. I'll try some other port numbers that work with other apps, but wondering what other hosting options are being used with ponzu.

TIA,
James

**Comment by nilslice** [comment]
I know of at least a few deployments including my own that use Debian or Ubuntu on Digital Ocean and AWS running Ponzu systems. 

How are you starting the Ponzu process? 

PS - I don't know much about managing Windows servers, so I may be the wrong person to help

**Comment by jksmithiii** [comment]
Thanks for help. All that's needed on windows is to just open a console and run exe. There is a keep alive issue (handle reboots, logouts, etc), so there's a couple of ways to deal with that in windows, but for testing purposes, I should be able to just run exe, and make sure whatever port is open.

**Comment by nilslice** [comment]
I see - and once you run the ponzu exe, do you see it listed in your activity monitor or process manager? i.e. It is actually started and running? 

Do you have the `ponzu` CLI installed on your deployment VM? or are you running the `ponzu-server.exe` manually, versus `ponzu run` ?

If you're running `ponzu-server.exe` manually, you may need to run it as `ponzu-server.exe serve` with the port and other flags you want to specify. Also be sure to have the `*.db` files and `cmd` directory within the exe's path so it can get the admin frontend code.

**Comment by jksmithiii** [comment]
I used ponzu run with defaults. I can access at 127.0.0.1:8080  fine. Just can't find it from a public address.

**Comment by jksmithiii** [comment]
Ok this is a port issue, even when local firewall is turned off. Need to open another port in the GAE firewall. Running fine now.

**Comment by nilslice** [comment]
Interesting! Would you mind writing a brief rundown of what you did to correct the issue so I can add it to the wiki somewhere? 

It would be helpful to anyone else running on GAE in the future. 

Thanks & glad it is working for you!!
