### ISSUE TITLE
Feedback: file uploads metadata storage and API 

### ISSUE THREAD

**Issue by nilslice** [ponzu-cms/ponzu#135]
Any feedback on the following would be much appreciated. Thanks!

I am working on an "uploads" db feature, and want to know if users have any issue w/ exposing API endpoint to see file data by slug (only), e.g.
![response](https://pbs.twimg.com/media/C-SRUFsVYAANNjD.jpg:large)

When uploading a file to your system (either as API client user or Admin), the system will now keep track of the files in the format pictured above in the database. Exposing the file data could be really useful to some apps, useless to many others, but I want to make sure it's not a risk to some. To avoid bot scraping easily, the `slug` is the only look-up key... no `id` which could just be iterated through.

**Comment by eticzon** [comment]
@nilslice I think this would be a useful feature. However exposing a "list all" uploads `GET` method might also be more useful, but like you this is open for abuse. The API could also give options for filtering requests based on other criteria such as `content_type`.

Are there any plans to secure other API endpoints with something like OAuth2 or JWT?

**Comment by nilslice** [comment]
@eticzon - thank you for the feedback. I agree that a "list all" method would be useful, but exposing it through the public API could lead to abuse, like you said. I should have added more detail.. with this feature, you will now be able  to view/delete your system's uploads through the Admin UI, so aside from API access (which we could create with an Addon), you should be able to achieve the same results as you're probably aiming for with the "list all" method.

There was a fair amount of support on this within the [#ponzu slack channel](https://gophers.slack.com/messages/C3TBV356D) -- please feel free to join us there! -- (no downvotes yet so to speak), so I think I will move forward with this as planned. This issue will stay open though so we can continue to discuss. If anyone else has any feedback, please don't hesitate to share!

Thanks,
Steve

**Comment by nilslice** [comment]
@eticzon  - sorry I didn't really notice this question before:
>Are there any plans to secure other API endpoints with something like OAuth2 or JWT?

You should already be able to implement a custom security model by implementing the `item.Hideable` interface on any content type you wish. To do this, add the `Hide(res, req) error` method from that interface (in [item.go](https://github.com/ponzu-cms/ponzu/blob/master/system/item/item.go)), and if the request fails your token check, return any error and the API response will not include your data. If the token check does pass, use `item.ErrAllowHiddenItem`  as the return value to tell the API handler that the response is OK to include you data. See the API implementation in [hide.go](https://github.com/ponzu-cms/ponzu/blob/master/system/item/item.go).

I am planning to extend the `item.Omitable` interface which allows you to selectively omit fields from content types thus keeping them from being exposed through the JSON API responses. Currently, you don't have access to the request, but the next iteration will and therefore enable you to check for a token of some sort before determining which fields to omit. If you have some time, take a look through that interface (it's super small) and its implementation in the `system/admin/api` package.

**Comment by eticzon** [comment]
> There was a fair amount of support on this within the #ponzu slack channel -- please feel free to join us there!
Thanks for the invite @nilslice.

+1 on the custom security model design! Nicely done! If you think there's there's room for standard auth mechanisms bolted as project Addons let me know, I can definitely help out.

**Comment by nilslice** [comment]
@eticzon - I would love to see a JWT/cookie auth addon for checking external client requests! I will open a new issue to start a discussion about an implementation if you would like. I'm currently working on a project that is built on Ponzu, and will need to incorporate some request authentication via JWT/cookies so we may be able to combine efforts if the addon is something you'd like to work on together.

I'll ping you on the new issue and we can pick up this thread over there!

**Comment by eticzon** [comment]
Cool! SGTM.

**Comment by nilslice** [comment]
PR #137 completes this.
