### ISSUE TITLE
Discussion: add /docs to repository

### ISSUE THREAD

**Issue by nilslice** [ponzu-cms/ponzu#139]
Hi all - I'm closing in on a comprehensive docs site for Ponzu (https://docs.ponzu-cms.org) and wanted to know if people want the current version of the HTML docs to be bundled into the `ponzu-cms/ponzu` repo.. Each time I cut a new release, I would add an updated version of the docs to the tree so the current documentation for your ponzu version is in every instance.

I'd also likely add a `$ ponzu --docs run`  flag too, which would just add a `/docs` route and handler to your current server so its available in the browser without any internet connection

Happy to take suggestions on other local hosted docs strategies. Thanks!

**Comment by olliephillips** [comment]
I like this idea. It's good UX. Like being able to run godoc offline -
you never need to - but it's nice to know you can, and that someone considered you that one time you do need it.

**Comment by nilslice** [comment]
On second thought, the `--docs` flag would run a separate server on `:1234` by default and serve static files from `/` route. 

e.g.
```bash
$ ponzu --docs run
Server listening on :8080 for HTTP requests...

visit `/admin` to get started.

docs available at `http://localhost:1234/`
```

**Comment by ivanov** [comment]
This makes sense to me, with the suggestion of going a step further and just having the entire docs repo live inside here. The markdown files are easier to read from a command-line interface.

**Comment by nilslice** [comment]
@ivanov - cool, we can do that. I'll just make sure the file server points to `docs/build` then instead of `docs` itself. Thx for the feedback! (and your PR on the docs, which I'm merging now)
