### ISSUE TITLE
go get github.com/ponzu-cms/ponzu/... fires error

### ISSUE THREAD

**Issue by torniker** [ponzu-cms/ponzu#144]
I get the following error when trying to get and build ponzu:

```
# github.com/ponzu-cms/ponzu/cmd/ponzu/vendor/golang.org/x/net/http2
src/github.com/ponzu-cms/ponzu/cmd/ponzu/vendor/golang.org/x/net/http2/transport.go:1074: undefined: httplex.PunycodeHostPort
# github.com/ponzu-cms/ponzu/system/api
src/github.com/ponzu-cms/ponzu/system/api/push.go:39: undefined: http2.ErrRecursivePush in http2.ErrRecursivePush.Error
```

Go version: `go1.8.1 darwin/amd64`

**Comment by nilslice** [comment]
@torniker - does this happen when running `go get` or `ponzu build`?

**Comment by torniker** [comment]
@nilslice it happens on go get

**Comment by nilslice** [comment]
@torniker did you recently upgrade to Go 1.8.1? if so what was the last version you had? I have tried re-installing the package on Mac, Linux and via Docker against 1.8.1 and it works. Maybe you have an older version of the http2 libs. Google found this:
https://github.com/grpc/grpc-go/issues/558

Did you try that?

**Comment by torniker** [comment]
@nilslice Thanks . it works now

**Comment by nilslice** [comment]
Ok - glad it is working!
