### ISSUE TITLE
Error making reference HTTP

### ISSUE THREAD

**Issue by excentro123** [ponzu-cms/ponzu#151]
Hello.
go 1.8.3, i'm doing all by video
created author, created book
and getting this:
2017/05/26 09:03:37 Error making reference HTTP request: http://localhost:8080/api/contents?type=Author&count=-1
2017/05/26 09:03:37 Error in ContentAll for reference HTTP request: http://localhost:8080/api/contents?type=Author&count=-1
2017/05/26 09:03:37 Error encoding data to options for Author unexpected end of JSON input
that am i doing wrong?
thanks

**Comment by nilslice** [comment]
@excentro123 - could you post the author.go and book.go files? We just made some semi-significant changes to the CLI and some internal code so I want to make sure it generated your content types correclty.

**Comment by excentro123** [comment]
[author.go.txt](https://github.com/ponzu-cms/ponzu/files/1030974/author.go.txt)
[book.go.txt](https://github.com/ponzu-cms/ponzu/files/1030976/book.go.txt)

**Comment by nilslice** [comment]
what did you set your Domain to in the config? is it set to localhost?

**Comment by nilslice** [comment]
(it can be updated in the System Configuration)

**Comment by excentro123** [comment]
changed domain to localhost and it works!
thanks

**Comment by nilslice** [comment]
Glad it's working!
