### ISSUE TITLE
Pagination with ponzu

### ISSUE THREAD

**Issue by excentro123** [ponzu-cms/ponzu#154]
Hello.
How would you implement pagination with ponzu?
I know, there are count and offset params, but ponzu does not return total number of results, neither next or previous page links like other good rest frameworks do.
So, all pagination calculations i have to do by myself? :)
thanks

**Comment by nilslice** [comment]
Currently, you'd need to do a `&count=-1` and find the length of the total results and then use the `count` and `offset` parameters to implement pagination with page numbers doing the calculations yourself.

You could implement your own handler that returns only the total count of any Content type, or even better work on a PR to add this feature.

**Comment by excentro123** [comment]
Thank You.
