### ISSUE TITLE
Failed to install Ponzu CLI

### ISSUE THREAD

**Issue by garyyao** [ponzu-cms/ponzu#155]
I just failed to install the CLI tool, the errors are as below, could you please help check, thanks!

$ go get github.com/ponzu-cms/ponzu/...
package github.com/ponzu-cms/ponzu/addons/github.com/bosssauce/reference
	imports golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package github.com/ponzu-cms/ponzu/addons/github.com/bosssauce/reference
	imports golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
# cd .; git clone https://go.googlesource.com/crypto /Users/Gary/GO/ws/src/golang.org/x/crypto
Cloning into '/Users/Gary/GO/ws/src/golang.org/x/crypto'...
fatal: unable to access 'https://go.googlesource.com/crypto/': Failed to connect to go.googlesource.com port 443: Operation timed out
package github.com/ponzu-cms/ponzu/addons/github.com/bosssauce/reference
	imports golang.org/x/crypto/bcrypt: exit status 128
package github.com/ponzu-cms/ponzu/cmd/ponzu
	imports golang.org/x/text/secure/bidirule: unrecognized import path "golang.org/x/text/secure/bidirule" (https fetch: Get https://golang.org/x/text/secure/bidirule?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package github.com/ponzu-cms/ponzu/cmd/ponzu
	imports golang.org/x/crypto/acme/autocert: unrecognized import path "golang.org/x/crypto/acme/autocert" (https fetch: Get https://golang.org/x/crypto/acme/autocert?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package github.com/ponzu-cms/ponzu/cmd/ponzu/vendor/golang.org/x/crypto/autocert
	imports golang.org/x/crypto/acme: unrecognized import path "golang.org/x/crypto/acme" (https fetch: Get https://golang.org/x/crypto/acme?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package github.com/ponzu-cms/ponzu/cmd/ponzu/vendor/golang.org/x/crypto/bcrypt
	imports golang.org/x/crypto/blowfish: unrecognized import path "golang.org/x/crypto/blowfish" (https fetch: Get https://golang.org/x/crypto/blowfish?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package github.com/ponzu-cms/ponzu/cmd/ponzu/vendor/golang.org/x/net/http2/h2i
	imports golang.org/x/crypto/ssh/terminal: unrecognized import path "golang.org/x/crypto/ssh/terminal" (https fetch: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
$ go get github.com/ponzu-cms/ponzu/...
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/crypto/bcrypt: unrecognized import path "golang.org/x/crypto/bcrypt" (https fetch: Get https://golang.org/x/crypto/bcrypt?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
# cd .; git clone https://go.googlesource.com/text /Users/Gary/GO/ws/src/golang.org/x/text
Cloning into '/Users/Gary/GO/ws/src/golang.org/x/text'...
fatal: unable to access 'https://go.googlesource.com/text/': Failed to connect to go.googlesource.com port 443: Operation timed out
package golang.org/x/text/secure/bidirule: exit status 128

**Comment by nilslice** [comment]
Which version of Go are you using? can you share the output of `$ go env`

**Comment by garyyao** [comment]
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"


Thanks your prompt response 👍

**Comment by nilslice** [comment]
Which version of Go?

**Comment by garyyao** [comment]
$ go version
go version go1.8.1 darwin/amd64

yes, it's 1.8.1

**Comment by nilslice** [comment]
hmmm.. do you have any other issues installing go dependencies?

does this url resolve on your network? https://go.googlesource.com/crypto/

**Comment by nilslice** [comment]
Hi - going to close this due to inactivity, but feel free to comment if there is still something wrong. Thanks!
