### ISSUE TITLE
[Query] Does Ponzu support run on my existing DB(Mysql)

### ISSUE THREAD

**Issue by garyyao** [ponzu-cms/ponzu#156]
@nilslice i already have an API system, i expect the CMS system can connect to my existing DB(mysql), and take the existing tables(models) as the entities, to manage the content. Seems Ponzu doesn't support this after checked the your documentation. Is my understanding correct? Thanks!

**Comment by nilslice** [comment]
Correct, Ponzu does not work as you had expected. That is an interesting idea though! :+1: You could use Ponzu, but would need to implement the `editor.Editable` interface on your models (as Content types in Ponzu), as well as register them to the `item.Types` map in their init() func. Then, the admin routes would need to talk to a different db.

Ponzu is responsible for both the DB ([Bolt](https://github.com/boltdb/bolt), an embedded data store), and the API to interact with its data.

**Comment by garyyao** [comment]
Hi Nilslice, thanks your explanation, look forward your further release, believe there're more interesting feature available, cheers!

**Comment by nilslice** [comment]
@garyyao - thanks, and feel free to join us on the #ponzu slack here: https://gophers.slack.com/messages/C3TBV356D/

and if you have ideas for features please let me know :)
