### ISSUE TITLE
Content with multiple arrays updates incorrectly

### ISSUE THREAD

**Issue by Paulsulli92** [ponzu-cms/ponzu#167]
I would like to have a content type with multiple arrays but it seem that it does not update properly.  I made a content type with this command:
`gen c listtest name:string list1:"[]string" list2:"[]string"`
Then built and ran and in the web editor added two entries to each list.  Upon saving, some of the entries in the first list changed to entries from the other list.  I am also unable to remove list entries: upon hitting save, removed entries reappear.  This was done with no changes to the listtest.go file.

**Comment by nilslice** [comment]
This is related to #59 - unfortunately I haven't had time to dig in and fix. I believe it is a JavaScript bug though, from within the editor package. The Go code for the RepeatController has some JavaScript that re-names the name attributes of each repeated input. 

If you get a chance to look into this, please let me know and feel free to ask any questions you have about the code. I'm on the road today and away through this weekend so I may be a bit slow to respond.

**Comment by nilslice** [comment]
@Paulsulli92 there is an active contribution pending that fixes this issue. Give me a day or so and I'll ping you when its ready.

**Comment by nilslice** [comment]
This should be good to go now -- if you find any more issues with it please let me know!
