### ISSUE TITLE
Set document to pending after edit?

### ISSUE THREAD

**Issue by Paulsulli92** [ponzu-cms/ponzu#174]
This isn't necessarily a bug report, but I have the requirement that all changes to documents need to be approved.   I would like to move a document back to a pending state when an edit is made, similar to how API uploads are made pending.  I don't see a way to do this in the documentation.  Is this workflow supported?

**Comment by nilslice** [comment]
Currently, that isn't supported. For clarification, does the document need to be accessible in its prior state while "pending" approval of the edits, or, should the document be hidden completely from the public content API until the edits are approved?

**Comment by nilslice** [comment]
(by "accessible" I mean publicly through the content API)

**Comment by Paulsulli92** [comment]
The document does need to be accessed in its prior state (approved version) while the new version is in the pending state.  So it's like two copies of the document but they could share an id or something.

**Comment by nilslice** [comment]
Ok, thanks for clarifying. How soon do you need this feature? I'm in the midst of a relocation, moving out of state so I have about 3-4 days before I'd really be able to look into implementing this. However, I don't think it should take that much to add a new interface that you could optionally satisfy to enable Drafts.

**Comment by olliephillips** [comment]
Closing this issue. No response to admin support and old. Please reopen if need to.
