### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by agung-wete** [ponzu-cms/ponzu#176]
Hi
i'm trying to use ponzu + hugo
is there any `hook` to call if content added / updated in ponzu (like github hook) ?

thank you

**Comment by nilslice** [comment]
There are a number of hooks provided by the `item.Hookable` package whose default implementations can be overriden by any of your Content types. 

The documentation for these are here: https://docs.ponzu-cms.org/Interfaces/Item/#itemhookable

There are brief descriptions for each hook on that page. Based on your comment, it sounds like you might want something like `AfterSave` and `AfterDelete`?  Let me know if it isn't clear how these should be implemented and I can try to expand. 

I'd be delighted to know how you are using Ponzu + Hugo together if you're able to share!

**Comment by agung-wete** [comment]
thank you
hugo has [datafiles](https://gohugo.io/extras/datafiles/) and [datadrivencontent](https://gohugo.io/extras/datadrivencontent/), i'm trying the best approach to combine with ponzu

**Comment by nilslice** [comment]
Cool - I didn't know about those features of Hugo, thanks for sharing!

Do the Hooks in Ponzu work for what you are trying to accomplish?
