### ISSUE TITLE
fork/exec ./ponzu-server: no such file or directory

### ISSUE THREAD

**Issue by pedrokoblitz** [ponzu-cms/ponzu#179]
I've followed the tutorial and was able to generate the review. But when I tried to run, I got this message. I've tried search for ponzu-server and found it in "/deployment/sysv".

First try: "Error: fork/exec ./ponzu-server: permission denied"
Second try (after chmod): "./ponzu-server: 12: ./ponzu-server: Syntax error: newline unexpected Error: exit status 2"

**Comment by nilslice** [comment]
Hi @pedrokoblitz -

Are you running this on the same machine you built the project or something like a remote host / VM?

Also, you mention `deployment/sysv`, are you running the `ponzu-server` through an init system or through the shell? Try this, or let me know if it is the same process you've done:

```bash
$ cd $GOPATH/src/YOUR_PROJECT_DIR
$ ponzu build
$ ponzu run
```

**Comment by pedrokoblitz** [comment]
I'm very very sorry. I thought "ponzu build" and "ponzu run" followed the same login as "go build" and "go run". Worked fine. Thank you.

**Comment by nilslice** [comment]
:) glad it is working for you now!

When you are ready to deploy, you can use the built `ponzu-server` binary to run itself:
```bash
$ ./ponzu-server run
```

This way you don't need to install Go or Ponzu on the target machine.
