### ISSUE TITLE
`.gitignore` ignores system files

### ISSUE THREAD

**Issue by shusson** [ponzu-cms/ponzu#185]
macOS 10.12.6
Ponzu v0.9.3

https://github.com/ponzu-cms/ponzu/blob/master/.gitignore#L3 will cause the system files in 
`cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/search` to be ignored.

This caused some unexpected errors (see below) when running the ponzu server after cloning the git repo (which was based on the generated files from `ponzu new`). 

unexpected error:
```2017/08/22 07:37:25 [search] MapIndex Error: Failed to MapIndex for Post, type doesn't exist```

**Comment by nilslice** [comment]
Ah, thank you for reporting this. I believe the recent commit will fix this. Please let me know if this is the case, thanks!

**Comment by shusson** [comment]
Thanks @nilslice, all good now
