### ISSUE TITLE
Question about implementing relations

### ISSUE THREAD

**Issue by jpic** [ponzu-cms/ponzu#191]
Hello everybody !

Ponzu looks really really cool, I like it a lot, feels very 2017 for a CMS ;)

However, I'd like to have a page editor where I can add/remove content blocks, each having a "image" and "body" text.

I didn't figure how to do that in Ponzu, but I can describe how I'd do it in Django: create another Block model with a relation to Page having "image" and "body" fields, add an inline in the Page admin so that I can add/edit/remove blocks in the Page admin form.

Is this possible, planned, started, or should I try from scratch to extend Ponzu to support this use case ?

Keep up the great work !

**Comment by nilslice** [comment]
Hi @jpic - glad you are liking Ponzu! 

If I understand your issue correctly, the best thing you could do at the moment would be to create a `Block` content type, and then reference them using a `reference.SelectRepeater` from something of a `BlockPage` content type.

If you were to generate this using the CLI, it would be something like:

```bash
$ ponzu gen c block name:string image:string:file body:string:textarea # or body:string:richtext 
$ ponzu gen c block_page name:string blocks:"[]@block",name  
```

Each content type has a "name" field just so you can give things names and recall them easier from within the CMS. They aren't totally necessary, but will probably help. You can omit them from the JSON API responses satisfying the [`item.Omittable`](https://docs.ponzu-cms.org/Interfaces/Item/#itemomittable) interface per content type. 

The downside is that you need to pre-create & save the Block then add it to the repeatable list of Block references from within a BlockPage type.

Try that out and let me know if it gets you any closer to where you're trying to go!

**Comment by jpic** [comment]
Thanks for answering @nilslice !

This is exactly what I'm looking for, except I'm looking to a form instead of the select heh ^^ I also believe we're going to need this kind of feature for ProductVariation in an e-commerce website.

So perhaps Ponzu could be enriched with a new repeater for forms, ie. reference.FormRepeater ?

**Comment by nilslice** [comment]
Sure thing! Right now, there isn't a way to "group" UI inputs within the CMS to represent a single value or reference. Simply, a UI field maps 1-to-1 with a content type struct field. 
This is why the reference concept is necessary when data types get more complex. One option to extend the reference concept would be to, like you mention, add a input func to the reference package that takes a variadic argument of other input funcs. For example, a reference.Group or reference.GroupRepeater would need to know the content type being referenced, then in your case would take an editor.File for the image and an editor.Textarea for the body. This "group" of UI would make up the referenced type. In the background, once an item is created, Ponzu would need to know that it should create a record for the reference Item type and set the value for the parent type's reference field to the reference's URI. Additionally, Ponzu would need to do more bookkeeping when that parent item is deleted or updated, so the internal references are also deleted (?) or updated. 

Truthfully, this is a use case where I have thought creating a custom admin app on top of Ponzu's Content API might be a better solution. It's a pretty complicated thing to do in a generic way for 100% of Ponzu users, but wouldn't be that bad to make specifically for your own product. 

Would love to know what you think about it and if you see more clear alternative solutions.

**Comment by olliephillips** [comment]
Closing this issue. It appears to be answered/resolved. Please reopen if not the case.
