### ISSUE TITLE
beginner questions

### ISSUE THREAD

**Issue by jarav** [ponzu-cms/ponzu#193]
I am new to Go and certainly to Ponzu too. I am also new to web development. I know a little bit of Javascript though. But I am liking Go and am inclined to use Ponzu rather than a CMS framework in, say, Python. I am planning to use it for a project. Just one or two rather stupid questions.

1. If I were to use Ponzu I would have to combine it with regular Golang web dev( say some other regular golang webdev framework) to handle things like cookies, sessions, logging in, etc, wouldn't I ? I have only a tiny idea of what those terms mean.

2. I can use regular javascript, can't I? I mean, I don't have to necessarily go for React or something like that.

Thanks.

**Comment by nilslice** [comment]
Hi @jarav - welcome to Go & Ponzu! 

>1. If I were to use Ponzu I would have to combine it with regular Golang web dev( say some other regular golang webdev framework) to handle things like cookies, sessions, logging in, etc, wouldn't I ? I have only a tiny idea of what those terms mean.

You can use any programming language you want for the "frontend" when working with Ponzu. Think of Ponzu as a HTTP accessible database..anything that can make HTTP requests can work with Ponzu - your Javascript on an HTML webpage, a PHP application, a Go application or iOS/Android app, etc. If you want to add functionality to the Content types you create with Ponzu, you will need to use Go.

>2. I can use regular javascript, can't I? I mean, I don't have to necessarily go for React or something like that.

You can use whatever you like - there is no need to pick a specific JS framework at all. The only requirement is that you can make HTTP / XHR calls from your javascript code to interact with Ponzu.

Hope that helps!

**Comment by jarav** [comment]
Sorry for the late reply. But Thanks. I just had a look at your go-client. As I said, I am new to web development and am reading a book on it( Web development with Go by Jon Calhoun) at the moment.

So here is my understanding so far. If I were to program in Go, I would have to make a server program in Go that handles the logging in of users, the authentication etc, independent of Ponzu. I will have to have a separate database that stores the user credentials and user information that this server program will handle. I guess this is the "front-end" you are referring to.  I will be using Ponzu only to create, store, and update custom content types that will be retrieved by my server program using the ponzu-cms api. For example, one custom content type might be an online quiz. This would be stored in Ponzu and my users would use my server program to take that online quiz. Is my understanding correct? Thank you for your time.

**Comment by olliephillips** [comment]
> I will have to have a separate database that stores the user credentials and user information that this server program will handle.

I think you're correct in your understanding. However, re the above - there's actually no reason you couldn't use Ponzu to store and retrieve User data.  Ponzu supports creation and updates of data over the API, as well as retrieval. You'd need to encrypt any sensitive data like password for storage in your Go app, before sending to Ponzu, but providing you are using TLS/https, the data would be secure sent and retrieved over the API.

**Comment by nilslice** [comment]
@jarav - as @olliephillips mentions, you wouldn't have to create a second Go server to handle users if you don't want to. Ponzu already has Users internally (you and your Admins), and you could add a Content type for users if you'd like. I saw your comment about the [bosssauce/access](https://github.com/bosssauce/access) addon and a better set of examples. I can try to get this done this week for you, or if you'd like, you could propose your specific use case and I can try to help with it.

**Comment by jarav** [comment]
Thank you @olliephillips, @nilslice . I did not see anything in the documentation about Users except for an Admin user in the Settings section. But I understand that I can create an User content type. Until I am more familiar with all of this, and with the access addon, I probably would be comfortable in using Ponzu just as a HTTP accessible database( which perhaps is not exposed to the end users at all),  as @nilslice was pointing out, to store the actual content types and leave all the user management to a different server program that I can make progressively sophisticated as I learn more. 

I might also need to restrict certain users to certain parts of a content type. For example, if I had an online quiz as a content type I wouldn't want the people who take the quiz to access the answers to the quiz, which are a part of the content type, directly. So I wouldn't want to expose the ponzu backend and the content access api in this case. This means that I will have to have a separate server program anyway to handle all that logic. I hope that this is a sensible approach. Please do point out if I am wrong.

@nilslice please do take your time on the access addon documentation.

**Comment by nanohard** [comment]
@jarav 
You would actually need to create both an `Admin` and `User` type, or just one user type and assign a group/role. Remember, this is just a backend; you would create the frontend yourself or use another framework and modify. The "admin" in Ponzu is for creating content using the Ponzu GUI, not for accessing it on the frontend application.

By creating the user roles in the backend you would then check for the role in the frontend application and query Ponzu based on that result.

Frontend example using golang code:
```go
var answers []string
if user.role == "admin" {
    answers = url.Get("https://example.com/api/test1/answers")
    return answers
} else if user.role == "user" {
    return "Nice try Ferris Bueller."
}
```

**Comment by olliephillips** [comment]
Closing this issue. It appears to be answered/resolved. Please reopen if not the case.
