### ISSUE TITLE
Set config from file

### ISSUE THREAD

**Issue by romeovs** [ponzu-cms/ponzu#197]
Love Ponzu, 

This is what I would've built if I had the time to do it!

One question: is it possible to configure a Ponzu install programmatically?
I usually run my client websites in a docker image so reading in immutable config from a file would super handy.

**Comment by nilslice** [comment]
Hi @romeovs  - 

Thanks for the kind words, glad you enjoy Ponzu!

It currently is not possible, but there was some work done by @martint17r a while back that could be worth now revisiting... We decided to hold off since there was a very large dependency graph created by an external package. If you'd like to share how you typically would load a config file to overwrite or partially configure a program along with any CLI flags, please do. 

cc/ @Sirikon for special attention to windows :)

**Comment by Sirikon** [comment]
If I understood correctly, it's just reading a file at start, for example from the path provided as a flag, so you can create a Docker image based on a Ponzu one which only changes the configuration file _or_ providing the config file using a Docker volume.

In the Windows part there shouldn't be any problem, as all paths are provided externally and Linux Docker images work on Windows using Hyper-V.

Will keep an eye on the conversation :) And would like an example or a link the previous work mentioned by @nilslice

**Comment by romeovs** [comment]
I just want to avoid *all* user interaction to get a site up and running. It should be possible to set up a website completely programmatically.

**Comment by nilslice** [comment]
@romeovs - I'd suggest simply adding a base `system.db` from your dev environment after locally configuring a site to your needs. 

The steps would possibly be as follows:

[local]
1. complete your Ponzu development
2. configure the running Ponzu system to your liking
3. to ensure there is no unnecessary data in `system.db` such as content, etc. Probably best to delete the `system.db` and re-configure without adding content data - make sure you to kill the ponzu-server process, then delete the file, and then re-run.

[docker]
1. add a step to your Dockerfile or whatever mechanism you build images to ADD/COPY the local `system.db` from your host to the container.
2. your container should then have a base `system.db` with the desired configuration saved. All configuration options available to you are within the [system/admin/config/config.go](https://github.com/ponzu-cms/ponzu/blob/master/system/admin/config/config.go#L12) file. Some of them can only be set from the command line at run-time, such as HTTP/HTTPS ports & Bind Address - so these will need to be added to your entry point or init script (i.e. `$ ./ponzu-server run --https --https-port=8443 --bind=0.0.0.0`). The admin user you create locally will be persisted, so ensure that the email/password is something you feel comfortable sharing with your client.

**Comment by Sirikon** [comment]
Yep, it's a way to make it work **today**. I would consider even if it's worth to have configuration inside the db that could be in a .yaml file, for example (For ease of use and readability for humans).
