### ISSUE TITLE
Need advice to clean up content's upload files when the content is deleted

### ISSUE THREAD

**Issue by ekkapob** [ponzu-cms/ponzu#199]
When I delete a content, its uploaded files don't get deleted. I've added `AfterDelete` hook in the content .go file but couldn't a method to get a full path of the files to delete with standard lib. I am not sure if this is the way to do it or there are other simple ways. I don't want to go to upload section and manually delete files everytime I delete a content. Please advise.

**Comment by nilslice** [comment]
Hi @ekkapob -

What is the output of fmt.Printf("%#v", t) - where 't' is the content type receiver on the AfterDelete method?

Also, what are the contents of the 'uploads' directory in your Ponzu project?

**Comment by ekkapob** [comment]
the Printf is 
```
&content.Promotion{Item:item.Item{UUID:uuid.UUID{0x39, 0x85, 0x9f, 0xf4, 0x5b, 0x42, 0x40, 0x6f, 0x93, 0x7a, 0x7, 0x86, 0xc8, 0xe7, 0x16, 0x8}, ID:4, Slug:"promotion-39859ff4-5b42-406f-937a-0786c8e71608", Timestamp:1508519565000, Updated:1508476365710}, Body:"wer", Photos:[]string{"/api/uploads/2017/10/1508476365-scan-1.jpeg"}}
```
I see the full-path now so I think I just use `upload/....` path to delete the file.
@nilslice

**Comment by nilslice** [comment]
Sounds good! 👍🏼
