### ISSUE TITLE
First install, 'ponzu run' gives: ./ponzu-server: no such file or directory

### ISSUE THREAD

**Issue by ajmas** [ponzu-cms/ponzu#201]
Just ran the instructions in the README and ran `go get github.com/ponzu-cms/ponzu/...`

Then I run `ponzu new testproject` and then finally `ponzu run`, at which point I get:

```
Error: fork/exec ./ponzu-server: no such file or directory
Usage:
  ponzu run [flags] <service(,service)>

Examples:
$ ponzu run
(or)
$ ponzu run --port=8080 --https admin,api
(or)
$ ponzu run admin
(or)
$ ponzu run --port=8888 api

Flags:
      --bind string      address for ponzu to bind the HTTP(S) server (default "localhost")
      --dev-https        [dev environment] enable automatic TLS/SSL certificate management
      --docs             [dev environment] run HTTP server to view local HTML documentation
      --docs-port int    [dev environment] override the documentation server port (default 1234)
  -h, --help             help for run
      --https            enable automatic TLS/SSL certificate management
      --https-port int   port for ponzu to bind its HTTPS listener (default 443)
      --port int         port for ponzu to bind its HTTP listener (default 8080)

Global Flags:
      --gocmd string   custom go command if using beta or new release of Go (default "go")

fork/exec ./ponzu-server: no such file or directory
```
A little experimenting shows I needed to do `ponzu build`. I am wondering whether it would be worth adding something about that in the command usage display? Something like 'Did you `ponzu build`?

**Comment by nilslice** [comment]
Hi @ajmas - 

Run `$ ponzu build` before  `$ ponzu run`. This will create the `ponzu-server` binary in your Ponzu project directory. 

You'll need to `$ ponzu build` whenever you save files with changes before `$ ponzu run` again.

**Comment by nilslice** [comment]
Check out the quickstart (also on the readme), and check out the docs for more information:
https://docs.ponzu-cms.org/Quickstart/Overview/
