### ISSUE TITLE
no go files in /home/user/go/src/github.com/ponzu-cms/ponzu

### ISSUE THREAD

**Issue by rebootcode** [ponzu-cms/ponzu#204]
After running first installation command,

`go get github.com/ponzu-cms/ponzu/…`

I get an error as:

`package github.com/ponzu-cms/ponzu: no Go files in /home/user/go/src/github.com/ponzu-cms/ponzu`

My Config are :- 

- Ubuntu 16.04
- go1.9.2

**Comment by nilslice** [comment]
@rebootcode - Sorry you're having trouble. I can't reproduce this. Are there any other details you can provide? Do other binary installs work from other packages you've run `go get` against?

**Comment by rebootcode** [comment]
Yes, I just ran `go get github.com/dgraph-io/badger/...` and it worked as it is supposed to be and I got `badger` binary in my`go-bin` directory.

**Comment by nilslice** [comment]
Hm. Could you try changing into the Ponzu source directory in your GOPATH and run `go install ./...` to see if that works?

**Comment by rebootcode** [comment]
Do you mean something like this :- 

1. `cd /home/user/go/src/github.com/ponzu-cms/ponzu`
2. `go install ./ ...`

**Comment by nilslice** [comment]
try running `go get -u github.com/ponzu-cms/ponzu/...` via copy / paste that exact command.

**Comment by rebootcode** [comment]
That worked (y)

**Comment by nilslice** [comment]
Great! 😁

**Comment by waltersenglish** [comment]
I get the same thing when I do ' go get'.  The files still download and everything seems okay but why does that show up?  For me, the error still shows up with ' -u ' 

go get -u github.com/JDStraughan/html5-snake
package github.com/JDStraughan/html5-snake: no Go files in C:\Users\dawnh\Desktop\BEN\Programming\Go\gocode\src\github.com\JDStraughan\html5-snake

**Comment by nilslice** [comment]
https://github.com/JDStraughan/html5-snake has no `.go` files to build in the repository. You should only use the `go` tools to run, build, install and test Go code. The `go` command will still fetch that repo (as it wraps `git`), but it's not Go code... so the next step it tries fails (building `.go` source files)

**Comment by Prabhudev-kannadoss** [comment]
> Great! 😁

when run  make sdk command   Inside Project directory facing this issue 

can't load package: package github.com/.../...: no Go files in /Users/mac/go/src/github.com/../..

please help me to fix this issue

**Comment by dadatuputi** [comment]
I had this error message - since I was starting fresh on a new install, I didn't have `build-essential` installed. go was failing on the make/build stage, but the error message wasn't accurate. Once I ran `# apt install build-essential` then `go get` finished successfully.

**Comment by MR-pentestGuy** [comment]
i have no src folder in my go when i download a tool from github where it should have github.com

**Comment by CouldBeThis** [comment]
Hi, I found this issue searching to solve the same in another repo. 

Also found [this reddit thread](https://old.reddit.com/r/golang/comments/kp3ysb/go_get_of_a_github_link_returns_no_go_files_in/) which may be of value.
