### ISSUE TITLE
Close the gzip writer in defer, not in Write impl

### ISSUE THREAD

**Issue by nilslice** [ponzu-cms/ponzu#205]
We should close the `*gzip.Writer` in a defer after it's [created](https://github.com/ponzu-cms/ponzu/blob/master/system/api/gzip.go#L29) instead of in the `Write()` implementation: 
https://github.com/ponzu-cms/ponzu/blob/master/system/api/gzip.go#L46

If anyone would like to do this, please feel free -- I'm away from my machine, but noticed this could be better while reviewing some code.

**Comment by robbawebba** [comment]
@nilslice I would love to help with this issue if it's still up for grabs!

**Comment by nilslice** [comment]
@robbawebba - go for it! Appreciate your help.

**Comment by nilslice** [comment]
Thanks again, @robbawebba!

**Comment by robbawebba** [comment]
Thanks @nilslice! I'm looking forward to more contributions to ponzu :)

**Comment by nilslice** [comment]
@robbawebba - fantastic! just added you to the #ponzu channel on Gopher's Slack. I look forward to working together more too.
