### ISSUE TITLE
Richtext editor

### ISSUE THREAD

**Issue by iharsuvorau** [ponzu-cms/ponzu#207]
_ponzu_ is a great project, my thanks to _Boss Sauce Creative, LLC_. I appreciate maintainers' work and will be glad to help as I can.

For now I'm exploring the docs and source code, trying to figure out if it is possible to rely on ponzu in my projects which require content management. 

I'm interested to use a _richtext field_ for text formatting but right now it seems that there is no enough basic styles for me, such as: 

* headings (h1−h6)
* blockquotes
* tables

It is [mentioned](https://docs.ponzu-cms.org/Form-Fields/HTML-Inputs/#editorrichtext) that the modified editor _Summernote_ is used for the `editor.Richtext` field. But I see that the Summernote editor has the dropdown menu 'Style' with headings and 'quotes' and a separate menu for tables — exactly what I'm looking for.

I wonder is it possible to modify the ponzu editor to include these menus in the admin UI: styles and tables?

**Comment by nilslice** [comment]
@iharsuvorau - thank you for the kind words & welcome to Ponzu! I would love to have your help on anything you think could be improved. 

The Summernote / Materialnote editor dependency can definitely be edited, and I believe it is only a matter of declaring more buttons where the editor is instantiated. I would suggest looking into the Summernote documentation to find where those options are. The `editor.Richtext` func could either be extended or copied and made into something more comprehensive from a feature standpoint.

**Comment by edDimensi** [comment]
Hi! Nice project! Maybe better change defautl RichText editor on https://alex-d.github.io/Trumbowyg/ this?

**Comment by nilslice** [comment]
Hi @edDimensi - thanks, I'm glad you like Ponzu!

I was not aware of the Trumbowyg editor. I appreciate you sharing it. I like that it can be extended through plugins, which is something I'm not sure Summernote, the existing richtext editor can do. 

I'll take a deeper look and see if it could be a good replacement. If you'd like to give it a try yourself, please feel free.

**Comment by gedw99** [comment]
Great to see so much interest is this. Ponzi is pretty unique - in a good way :)

What about the quill editor ?
I have been using it via dart and running it on web and flutter. I really like the fact that it saves the data is a highly granular way that is parsable so you can easily use the same for PDF printing.
It also has alot of usage and very mature.
The other thing it has is streaming events. This makes it easy to built collaboration like you get with google docs.

I am currently playing with compiling Hugo to run on mobiles with a web and flutter interface. The way I see things is that I can use Ponzi as a solid generic CMS and then put more user specific functionality on top of it in the flutter or web UI or wrap Ponzi API slightly with any special workflows needed.

As far as I can tell no one has done this insanity yet and I would be interested to hear others thoughts on the benefits this brings to Ponzi users in general. Maybe it's something worth merging back in. Maybe my idea is good but has some hurdles I am not away if yet.

**Comment by nanohard** [comment]
There is indeed a way to add those fields. After creating a project, edit the file:
`cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/management/editor/elements.go`

`['style', ['style']]` adds the headings and paragraph styles.

Here is my config:
```
toolbar: [
    ['style', ['style']],
    ['font', ['bold', 'italic', 'underline', 'clear', 'strikethrough', 'superscript', 'subscript']],
    ['fontsize', ['fontsize']],
    ['color', ['color']],
    ['insert', ['link', 'picture', 'video', 'hr']],					
    ['para', ['ul', 'ol', 'paragraph']],
    ['table', ['table']],
    ['height', ['height']],
    ['misc', ['codeview']]
],
```

I may submit a PR if I can find where it's generated, probably the same file name, as it's a basic thing to have.
