### ISSUE TITLE
put or post a record?

### ISSUE THREAD

**Issue by ihxzihxz** [ponzu-cms/ponzu#214]
how to put or post a record with api?

**Comment by nilslice** [comment]
You'll need to implement the api.Creatable interface on your content type:

https://docs.ponzu-cms.org/Interfaces/API/#apicreateable

Then, issue a POST request to the Ponzu server at its create endpoint:
https://docs.ponzu-cms.org/HTTP-APIs/Content/#new-content

There is much more documented on that website -- let me know if you have trouble with any of the above.

**Comment by ihxzihxz** [comment]
OK copy that
