### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by iharsuvorau** [ponzu-cms/ponzu#221]
Trying to `go get` on another machine:
```
$ go get github.com/ponzu-cms/ponzu/...
```

receive the error:
```
# github.com/ponzu-cms/ponzu/system/tls
../../ponzu-cms/ponzu/system/tls/enable.go:79: m.HTTPHandler undefined (type autocert.Manager has no field or method HTTPHandler)
```

**Comment by nilslice** [comment]
Thx for reporting this. Can you try with the `-u` option?

`go get -u github.com/ponzu-cms/ponzu/...`

**Comment by iharsuvorau** [comment]
@nilslice yes, it's okay now with `-u` and without it, thank you.

**Comment by nilslice** [comment]
Ok, thank you.
