### ISSUE TITLE
Add-on Idea/Help: Include styles/scripts once per editor page load

### ISSUE THREAD

**Issue by jharkins** [ponzu-cms/ponzu#236]
Howdy! Enjoying ponzu so far - writing a little addon that I'll contribute once I'm done.

My current need is including JS/CSS once per editor page load. I'm creating some editor elements that need external JS/CSS libraries, but they only need to be loaded one time - each individual editable field will have some additional rigging JS, which is intuitive to include per element (just add via html.WriteString, as demo'd in existing addons). 

What I was looking for is something like editor.AddPageScript(["<script>...</script>"]) and editor.AddStyle(["<style ... >", ...] and have that included in the editor experience.

Am I missing something (likely...)? I could write some JS that ensures that these assets are loaded once and only once, but that feels clunky in this case, as it'd be repeat for N number of fields.

**Comment by nilslice** [comment]
@jharkins - I'm happy you're looking into this, as it is definitely something we need to address. You're not missing anything as far as included features.. there is currently no built-in support for the feature you're describing. 

There was some discussion around how to 1. include assets for addons and editors, and 2. how to best serve those files from an internal file server in issue #165. Give that a read and see if it helps. We're not locked-in to any of those ideas, so don't let it steer you in one direction or another.. just wondering if we're on the same general page.

**Comment by olliephillips** [comment]
Hello @jharkins I appreciate this is an old issue now, but were you able to progress your add-on? If not, can Ponzu community help in any way?

**Comment by olliephillips** [comment]
Going to close this one. Feel free to reopen to restart the discussion
