### ISSUE TITLE
Extending the rich text editor to add code

### ISSUE THREAD

**Issue by msmshazan** [ponzu-cms/ponzu#238]
Is it possible to extend the rich text editor to add code with syntax highlighting?
If so then how?
I know it's possible to add code using the quill editor.

**Comment by nilslice** [comment]
@msmshazan  - it is possible, but you would need to load a plugin. The rich text editor is created using a custom version of [Summernote](https://summernote.org/) called [Materialnote](https://github.com/Cerealkillerway/materialNote)

You technically can add options to this, but it might be easier to just implement your own input field type. I'm sorry I don't have more direction for you, but please feel free to keep this issue open and track progress or ask questions if you decide to create your own input type. For examples of existing Ponzu editor inputs, see the Richtext implementation here: https://github.com/ponzu-cms/ponzu/blob/master/management/editor/elements.go#L217

**Comment by olliephillips** [comment]
Closing this issue. It appears to be answered/resolved. Please reopen if not the case.
