### ISSUE TITLE
Creating a datetime field in Ponzu

### ISSUE THREAD

**Issue by joesb** [ponzu-cms/ponzu#244]
I'm wondering how to create a content field for a datetime e.g. opening/closing dates of an event. Ideally it would be formatted into year, month, day (etc.) fields in the UI – taking some inspiration from the content publishTime UI, maybe. Granularity of field elements might be adaptable in some way.

Any resources or pointers on how to do it? (I'm new to Go and Ponzu, and hoping to learn some Go by working with Ponzu.)

Many thanks, in anticipation.

**Comment by nilslice** [comment]
@joesb - You can add any arbitrary HTML attributes to the inputs exported from the `editor` package. Could you try adding the `type` attr set to `date` in the input function? 

for example:
```go
        editor.Field{
            View: editor.Input("StartDate", p, map[string]string{
                "label":       "StartDate",
                "type":        "date",
                "placeholder": "Enter the Author here",
            }),
        },
```

**Comment by joesb** [comment]
Thanks for this. I'll have a got and see how far I get.

**Comment by nilslice** [comment]
@joesb - any luck? going to close out this issue unless you're having problems with it :)

**Comment by joesb** [comment]
Sorry @nilslice - I've not had a chance to get onto it again since asking. Gah!

Do please feel happy closing this issue and I can always ask more questions at a later date. Thanks a gazillion for your help.

**Comment by nilslice** [comment]
No worries -- I'll leave it open, not a problem at all. Happy to help!

**Comment by vinceyoumans** [comment]
new to ponzu...   is there a way to extend this field by doing some calculations on the date field after submit?  for example.  check if its between two time periods, or confirm its a valid date based on a lookup?  O perhaps post submit to convert the date format to another format...  or do some calculation on the date to populate another field?

**Comment by joshdstockdale** [comment]
@nilslice Your solution worked perfectly for me.

**Comment by olliephillips** [comment]
Closing this issue. It appears to be answered/resolved. Please reopen if not the case.
