### ISSUE TITLE
Empty FileRepeater field results bunch of {timestamp}- 0 byte files

### ISSUE THREAD

**Issue by mkungla** [ponzu-cms/ponzu#253]
Somewhere should be a check that was there actually file added to FileRepeater field 

e.g err when result string is empty
https://github.com/ponzu-cms/ponzu/blob/c9a6c2ef34d4c290223963d6e836926c6b58eb1b/system/item/item.go#L316 

or return err with NormalizeString when creating filenames
https://github.com/ponzu-cms/ponzu/blob/c9a6c2ef34d4c290223963d6e836926c6b58eb1b/system/item/item.go#L360

or maybe check here `if filename == "" { continue }`
https://github.com/ponzu-cms/ponzu/blob/8319420935c223e432bc4c386bd7d26b03f01b47/system/admin/upload/upload.go#L63-L68

**Comment by nilslice** [comment]
Hi - sorry for the delayed response! Thanks for pointing these out. Did you have a PR you'd like to make for this, or were you just pointing out some issues?

**Comment by mkungla** [comment]
I was just pointing it out since I haven't used ponzu much so I'm not sure where would be the best place to implement that check.

**Comment by nilslice** [comment]
@mkungla - cool, thanks for the heads up! I have limited time over the next couple weeks, but I can take a look soon. If you find some time to dig in and need help, feel free to try and ask questions here or on the [Ponzu channel](https://gophers.slack.com/messages/C3TBV356D) in the Gopher's slack.

**Comment by olliephillips** [comment]
Related to #261? I didn't test a FileRepeater

**Comment by olliephillips** [comment]
I've tested FileRepeater and I still don't get empty files. 

Looking through the release history I can't see that this has been addressed, but I can't replicate. 

Going to close this issue and #261. Please reopen if you believe this is still an issue.
