### ISSUE TITLE
Ponzu CMS on DigitalOcean droplet

### ISSUE THREAD

**Issue by spmitch2980** [ponzu-cms/ponzu#254]
I'm very interested in setting up Ponzu CMS on a live server, but I'm having trouble getting it to bind to the port 443. I keep getting the following error/

Enabling HTTPS...
Server listening on :443 for HTTPS requests...
Using  as host/domain for certificate...
NOTE: if the host/domain is not configured properly or is unreachable, HTTPS set-up will fail.
Using  as contact email for certificate...
2018/05/23 04:20:42 listen tcp :443: bind: permission denied
Error: exit status 1

I'm guessing it is a config error, also I'm using HaProxy, any help would be great

Thanks
Sean

**Comment by nilslice** [comment]
I believe you are trying to run the ponzu server as an "unprivileged" user, trying to bind to a "privilidged" port such as 443. If so, try running it with `sudo`

I have not tested a ponzu server behind HAProxy before, so I apologize if you run into problems that I can't address well.

**Comment by spmitch2980** [comment]
Thanks for you help, I got it working, it was an issue of the reverse proxy, but now none of the css is loading, any idea of where to fix this issue?

**Comment by spmitch2980** [comment]
Thanks again, If I can start Ponzu with --https flag, I think I would be good, but when I try I get the following output/

ponzu run --port=9000 --https admin,api
Enabling HTTPS...
Server listening on :443 for HTTPS requests...
Using <MY DOMAIN> as host/domain for certificate...
NOTE: if the host/domain is not configured properly or is unreachable, HTTPS set-up will fail.
Using admin@<MY DOMAIN> as contact email for certificate...
2018/05/24 19:32:48 listen tcp :443: bind: permission denied
Error: exit status 1

side note the domain already has a Let'sEncrypt cert for the domain

**Comment by nilslice** [comment]
If you run with the `--https` flag, the only option is on port 443, and it will override the port you specify. 

Unless you absolutely must have encryption between your proxy and the ponzu instance, I'd suggest dropping the `--https` flag. Otherwise you'll need to fork Ponzu and change the default behavior. This is assuming your SSL termination is being done by the proxy.

**Comment by spmitch2980** [comment]
Seems to be working but getting: acme/autocert: host not configured

sudo ./ponzu-server run --https
Enabling HTTPS...
Server listening on :443 for HTTPS requests...
Using http://MYDOMAIN.com as host/domain for certificate...
NOTE: if the host/domain is not configured properly or is unreachable, HTTPS set-up will fail.
Using admin@MYDOMAIN.com as contact email for certificate...
Server listening at localhost:8080 for HTTP requests...

Visit '/admin' to get started.
2018/05/24 22:53:34 http: TLS handshake error from MYIPADDRESS:55182: acme/autocert: host not configured
2018/05/24 22:53:35 http: TLS handshake error from MYIPADDRESS:55183: acme/autocert: host not configured

**Comment by nilslice** [comment]
is your host configured to `http://MYDOMAIN.com ` or containing the "http://" within the settings of your CMS? 

it should only be the domain/host, not including the "http://", just MYDOMAIN.com

**Comment by nilslice** [comment]
Hi @spmitch2980 - I am going to close out the issue, but please let me know if you have not solved this by opening a new issue. Thanks!
