### ISSUE TITLE
customize a feature.. looking for strategies...

### ISSUE THREAD

**Issue by vinceyoumans** [ponzu-cms/ponzu#255]
I am new to Ponzu and still looking at code base.  My situation is that I have several external Data sources that I consume with GoLang and consolidate in a BoldDB.  Then I found Ponzu and thought I would give it a try.  My question is this...

1...  A strategy to create custom modules that I can execute with a button click on the admin screen.   The fist will be a function that consumes a JSON file, chops it up and populates the PONZU system.  So where would I start.  I was thinking of just writing a separate program and submitting to ponzu over a rest call.  but It would be nice to incorporate the function in a screen.  any examples, ideas?
2...  I was also going to do a SQL injector to pump data into a SQL server and or a Messaging server.

thanks..

**Comment by nilslice** [comment]
Hey @vinceyoumans - 

1. check out: https://github.com/bosssauce/fbscheduler 
This is an example of a Ponzu addon. you can make an addon for your CMS UI which interacts with the system db. 

2. will need more context to have any thoughts here. 

Thanks!

**Comment by olliephillips** [comment]
Closing this issue. It appears to be answered/resolved. Please reopen if not the case.
