### ISSUE TITLE
How to display videos?

### ISSUE THREAD

**Issue by Etweyede** [ponzu-cms/ponzu#256]
What if i want to display videos on my app/site? How do you do it?

No where to ask the question so beasr with me if this is the wrong avenue!

**Comment by nilslice** [comment]
Hi @Etweyede -

Your video would be sent by Ponzu as an HTTP response when an app or website makes a request for it. The request would be made to the URL stored for the video in the Ponzu database. You can get the video's URL from the content API. 

Once you have the video URL, you would use that as the source URL of your video player (such as a `video` HTML element)

Sorry if I misunderstood your question!

**Comment by olliephillips** [comment]
Closing this issue. It appears to be answered/resolved. Please reopen if not the case.
