### ISSUE TITLE
Replace package satori/go.uuid

### ISSUE THREAD

**Issue by josselin-c** [ponzu-cms/ponzu#257]
This issue has been opened automaticaly because we think you are using satori/uuid in your code. Unfortunately, satori/uuid has a critical defect where it doesn't generate random UUIDV4s satori/go.uuid#73 and should be replaced as the maintainer has been unresponsive for 5 months with the bug still open. Alternative packages you should consider: https://github.com/google/uuid https://github.com/pborman/uuid

**Comment by nanohard** [comment]
The most recent maintained version is:
[github.com/gofrs/uuid](https://github.com/gofrs/uuid)

**Comment by nilslice** [comment]
@josselin-c, thank you for pointing this out. As mentioned by @nanohard, `gofrs/uuid` looks like a well-maintained replacement for the original `satori/uuid`, and it has been updated.
