### ISSUE TITLE
checkbox CLI parameter doesn't work

### ISSUE THREAD

**Issue by everyx** [ponzu-cms/ponzu#259]
`ponzu gen content account IsValid:"bool":checkbox`

I can only get a label with nothing, how to display a checkbox in admin create page.

**Comment by nanohard** [comment]
The correct semantic is `string`:
`ponzu gen c account IsValid:string:checkbox`

Then go into the `account.go` file model. You will find the example commented out; just add your checkboxes. Also, this is already a group of checkboxes, so no need for a slice of strings when using `editor.Checkbox`.

Here is the code generated from that command:
```
type Account struct {
	item.Item

	IsValid string `json:"is_valid"`
}

...

editor.Field{
    View: editor.Checkbox("IsValid", t, map[string]string{
        "label": "IsValid",
    }, map[string]string{
        // "value": "Display Name",
    }),
},
```

**Comment by everyx** [comment]
@nanohard Thanks, that's what I need. :)
