### ISSUE TITLE
-su: ponzu: command not found

### ISSUE THREAD

**Issue by realfakeelonmusk** [ponzu-cms/ponzu#278]
Tried installing it on Debian 9 stretch
This is my go env output, I am new to go so please lmk what am I doing wrong

```

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work/bin"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by nanohard** [comment]
Your `GOPATH` looks wrong, unless you're dir structure looks like `/root/work/bin/src/github.com/ponzu-cms/ponzu` and `/root/work/bin/bin/ponzu`. The latter is what you need to run the command `ponzu`, and the `GOPATH` would also need to be in your shell's `PATH` env var.
If you can run `/root/work/bin/bin/ponzu` then it's just missing from your shell `PATH`.

**Comment by nanohard** [comment]
Give this a read: [http://www.ryanday.net/2012/10/01/installing-go-and-gopath/](http://www.ryanday.net/2012/10/01/installing-go-and-gopath/)

Closing the issue; not related to ponzu. For further assistance please reach out via another source, maybe Slack.

**Comment by realfakeelonmusk** [comment]
Fixed it because I found it
