### ISSUE TITLE
System/backup does not follow symlinks

### ISSUE THREAD

**Issue by vkuznecovas** [ponzu-cms/ponzu#288]
I'm running ponzu with a symlinked upload directory. When trying to fetch the upload backup through API, the following log line appears on the running ponzu:

`read uploads: is a directory`

The response still returns a 200 success, but with a malformed body that's missing the proper contents. 

This is caused by system/backup ArchiveFS function. The ArchiveFS does NOT check for symlink in the provided basedir therefore ends up walking over itself and crashing. Since the error is not handled properly the message is logged and the 200 status is still reported.

**Comment by nilslice** [comment]
Hey -- thanks for reporting! I'll check out your PR #289 and run some tests, then check back with any findings or merge in. Thank you for the contribution!

**Comment by vkuznecovas** [comment]
@nilslice since you've merged the PR, I'm closing this. Thanks!
