### ISSUE TITLE
error command ponzu on windows 10

### ISSUE THREAD

**Issue by mytrix-technology** [ponzu-cms/ponzu#290]
I have error after install ponzu CLI
"'ponzu' is not recognized as an internal or external command,
operable program or batch file."

my GOPATH : echo %GOPATH%
E:\laragon\usr\go

my GOROOT : echo %GOROOT%
E:\laragon\bin\go\go1.9.2

Can anybody solve my problem??
Thanks

**Comment by nilslice** [comment]
Hi @mytrix-technology - would you try running the `go get` again, but hand-type (don't copy/paste) the last `...` characters into the windows terminal? 

`go get -u github.com/ponzu-cms/ponzu/...` 

I _think_ I have heard an issue before where the `...` is copied on Windows as a unicode character and thus not properly interpreted by the go tool

**Comment by ahu** [comment]
I have the same issue on macOS too. I tried servel times and never see the ponzu under the bin folder.

I resolve this by cd into ponzu and run `go install ./...`. Then the executable ponzu available.

**Comment by nilslice** [comment]
@mytrix-technology @ahu - this may be related to the regression introduced (and now solved) in recent Go versions:

https://github.com/golang/go/issues/29241

Try upgrading to the latest version of Go, hopefully it will fix this issue.

**Comment by yanshah** [comment]
just delete the 3 dots and retype it , it will work on windows

**Comment by nilslice** [comment]
confirmed @yanshah's solution is correct. thank you!

**Comment by Darksidis** [comment]
> I have the same issue on macOS too. I tried several times and never see the ponzu under the bin folder.
> 
> I resolve this by cd into ponzu and run `go install ./...`. Then the executable ponzu is available.

This worked for me
