### ISSUE TITLE
get all records of type...

### ISSUE THREAD

**Issue by tomazbracic** [ponzu-cms/ponzu#293]
Hi,

passing through the Ponsu documentation. Can't seem to find ...is there an option for fetching all the records of one content type?

For instance, I have a type Author. Can I retreive all authors with 1 GET call?

Best,
Tomaz

**Comment by nilslice** [comment]
Hi @tomazbracic - 

See here for reference to this endpoint: https://docs.ponzu-cms.org/HTTP-APIs/Content/#get-contents-by-type
