### ISSUE TITLE
Advisory from Netsparker - Ponzu CMS - 0.9.4

### ISSUE THREAD

**Issue by DanielBishtawi** [ponzu-cms/ponzu#294]
Hello,

While testing the Netsparker web application security scanner we identified vulnerabilities in Ponzu CMS. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details.

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by nilslice** [comment]
Emailed. Thank you!
