### ISSUE TITLE
Ponzu Team workflow

### ISSUE THREAD

**Issue by olliephillips** [ponzu-cms/ponzu#303]
I'm very happy to be part of Ponzu team, but might it be worth documenting somewhere what we can help with over and above the norm.

For example:

- Many open issues appear resolved and might be closed just for focus. Should team members do this? Is this helpful? I took the liberty on one open unanswered issue, but I was not sure of my ground.

- I think we can also merge pull requests. Should we? Should we exclude our own?

There are probably others. I just don't want to assume anything, and a bit guidance on etiquette would be a massive help.

**Comment by nilslice** [comment]
I'm really glad to have your involvement, and fully support the Team being able to take more action on issues and PRs. 

> Many open issues appear resolved and might be closed just for focus. Should team members do this? Is this helpful? I took the liberty on one open unanswered issue, but I was not sure of my ground.

If Team members are willing and able, I would _love_ to have the assistance to get issues taken care of, whether it is helping users, solving bugs, or closing/linking to repeats.

I really appreciate your help already on this, and it is by all means welcomed to step in wherever you feel like you can.

> I think we can also merge pull requests. Should we? Should we exclude our own?

I have just added some protection rules to the `master` branch. If you want to merge a PR (which is absolutely fine by me), we should merge into a rebased `ponzu-dev` branch (so it works with the tooling, until that's fixed 😄 ), and tested before creating a new PR from `ponzu-dev` into `master`. 

`master` now requires 1 approval before being merged - and I *think* Team members can all participate in this, but the final PR creator cannot merge their own PR (with the exception of the admin, currently just me). 

Let me know what you think of this, and we can even do a test PR to feel it out. 


cc/ @ponzu-cms/team

**Comment by olliephillips** [comment]
That works from my perspective.  It's the nature of open source that we must pick-up and put-down projects, so it's good to have a bit of clarification about how team members can use their additional privileges when we are in the (ponzu) zone :)

**Comment by olliephillips** [comment]
Closing this issue. Ponzu team in the loop and there is more clarity in team's remit
