### ISSUE TITLE
Ponzu support for snaps

### ISSUE THREAD

**Issue by igorljubuncic** [ponzu-cms/ponzu#306]
Hello,

I had a brief conversation with Ollie, and he suggested I open an issue.

I'd like to ask you to add support for building snaps of ponzu.

Snaps are cross-distro packages, self-contained and with automatic updates, available through the Snap Store to millions of users. Snaps are supported on more than 41 distros and multiple architectures.

If you're interested, I can open a PR with detailed instructions on how to create a snap of ponzu. I've built it myself, and it works fine.

Let me know if you have any questions, or if you need more info on snaps, the ecosystem, or the build system.

Thanks!

**Comment by nilslice** [comment]
Hi @igorljubuncic - 

Please do open a PR with info on this, and we'll take a look. Thank you!

**Comment by olliephillips** [comment]
PR is in was submitted and has been merged into ponzu-dev. Closing this.
