### ISSUE TITLE
Few broken URLs in the code and docs

### ISSUE THREAD

**Issue by benduncan** [ponzu-cms/ponzu#310]
Loving the work on Ponzu, keep it up!

Seems a few links broken however:

addons.ponzu-cms.org - Dead, referenced in docs and plugins.
https://www.bosssauce.it/ - On admin footer, broken too.

**Comment by olliephillips** [comment]
Hey there, I think the first of these is a known issue that just hasn't been addressed yet. Re the second, please would you clarify - the link in the ponzu server application's `/admin` footer is ok for me so you probably have spotted something else?  If you're able to, and have the time, a fix for these via PR would be great.  The main dev behind Ponzu is pretty busy ATM, so community contributions to the Ponzu project are especially welcome.

**Comment by nilslice** [comment]
@benduncan @olliephillips - 

thanks for pointing these out! As Ollie mentioned, the first is indeed a known issue. I'd love to follow through with the "Addon Marketplace" I had initially set out to build... however, the second link should now resolve just fine -- I had accidentally reverted some DNS records in a registrar migration and the broken link was a sad side effect. 

I'm going to close this issue, as it is (half) resolved... Appreciate the heads up!
