### ISSUE TITLE
Shortcodes addon

### ISSUE THREAD

**Issue by olliephillips** [ponzu-cms/ponzu#312]
Just an FYI. I've just put a shortcodes add-on on github. It'll need the v0.11.0 release, which isn't available yet, or you can build/install Ponzu from current master branch.  Feedback welcome.

https://github.com/olliephillips/shortcodes

**Comment by nilslice** [comment]
@olliephillips - very cool! Love seeing some of those addon features being put to use 😃 

Is there anything you're waiting for to do a v0.11.0 release? Just making sure I'm not a blocker

**Comment by olliephillips** [comment]
Thanks steve, no nothing blocking, master is all set now, and might be worth waiting for pr #309 before release. That'll box off all the community contributions to Ponzu codebase as far as I can see
