### ISSUE TITLE
Date or Time field -- how to?

### ISSUE THREAD

**Issue by Tom2Terrific** [ponzu-cms/ponzu#315]
My database needs several DATE type fields, but I'm unable to successfully create when using type "date" or "time".  How to manage start date, end date, etc?

cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/content/commtest.go:18:13: undefined: date
or
cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/content/commtest.go:18:13: undefined: time

**Comment by nilslice** [comment]
@Tom2Terrific - you can likely use a custom input in the CMS and create an `<input type="date" name="start_time"/>` etc, and it should serialize into a `time.Time` in Go, which you can use as the content type field. this is not tested, and you might need to convert the date from the HTML form to Go `time.Time` in-between the form submission and the CMS saving the data (if that's the case, look at the [Hooks Interface APIs](https://docs.ponzu-cms.org/Interfaces/Item/#itemhookable))

**Comment by Tom2Terrific** [comment]
Steve:

I appreciate your response, but am quite new to Go.  (programmed in 
Clipper from late 80's to 2009) That's why I was delighted to discover 
such a high level tool as ponzu.  It solved my quest for a login (to 
know whether the user is admin or not), and to nicely display the 
database maintenance.

Your response is a bit too cryptic, so may I get clarification 
(certainly I'm not the first or only to want date fields as part of the 
database?)

Apparently the modifications would be made to generate.go, or to 
gen-custom.tmpl?  The build doesn't actually complete, though I do get 
commtest.go (the name I chose was commtest), and there is a date type in 
the struct there:

type Commtest struct {
         item.Item

         Title      string  `json:"title"`
         Author     string  `json:"author"`
         Rating     float64 `json:"rating"`
         Body       string  `json:"body"`
         WebsiteUrl string  `json:"website_url"`
         Startdate  date    `json:"startdate"`
}


Thanks,
Tom

**Comment by olliephillips** [comment]
@Tom2Terrific there's no builtin data type in Go. To store a date or time you'd want to use the ```time.Time``` type in place of where you have ```date```.  That should build.

**Comment by Tom2Terrific** [comment]
Ollie:

Well, here is what I think you meant to do (as I had previously tried 
"date" and "time" without success):

tom@server:~/go/src/github.com/nilslice/commtest$ ponzu generate content 
commtest title:"string" author:"string" rating:"float64" 
body:"string":richtext website_url:"string" startdate:"time.Time"

which produced this struct:
type Commtest struct {
         item.Item

         Title      string    `json:"title"`
         Author     string    `json:"author"`
         Rating     float64   `json:"rating"`
         Body       string    `json:"body"`
         WebsiteUrl string    `json:"website_url"`
         Startdate  time.time `json:"startdate"`
}


tom@server:~/go/src/github.com/nilslice/commtest$ ponzu build
# 
github.com/nilslice/commtest/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/content
cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/content/commtest.go:18:13: 
undefined: time
Error: exit status 2
Usage:
   ponzu build [flags]

Examples:
$ ponzu build
(or)
$ ponzu build --gocmd=go1.8rc1

Flags:
   -h, --help   help for build

Global Flags:
       --gocmd string   custom go command if using beta or new release of 
Go (default "go")

exit status 2

Thanks,
Tom
======================================================

**Comment by nilslice** [comment]
@Tom2Terrific - 

`time.time` is not a valid type, you mean to write `time.Time` (capitalized symbols in Go modules indicate their visibility ("public/private", or in Go "exported/unexported").

However, this is not a good forum for general Go help. I'd suggest joining the Gopher's Slack and asking general questions like this in the #newbie or #general channel.

Join by clicking here: https://invite.slack.golangbridge.org
