### ISSUE TITLE
Error during go get

### ISSUE THREAD

**Issue by itwars** [ponzu-cms/ponzu#32]
Hello,

I was very excited to test it but I got an issue:
```
go get github.com/ponzu-cms/ponzu/...
# github.com/ponzu-cms/ponzu/system/api
../../../golang/src/github.com/ponzu-cms/ponzu/system/api/push.go:14: undefined: http.Pusher
```

**Comment by nilslice** [comment]
Hi @itwars  - 

That is an error indicating you need to install Go 1.8 -- the http.Pusher interface is not part of Go 1.7 or below. 

Luckily, there is an easy way to get the release candidate for 1.8: 

Run the following commands:

```bash
$ go get golang.org/x/build/version/go1.8rc1
$ go1.8rc1 download
# make sure it was downloaded, then: 
$ go1.8rc1 get github.com/ponzu-cms/ponzu/...
``` 

Because of this requirement, you will also need to run the Ponzu build step with go1.8rc1. In order to do that, use the `gocmd` option once you have the ponzu CLI installed:

```bash
$ ponzu -gocmd=go1.8rc1 build
```

Let me know if there are any other issues.

**Comment by nilslice** [comment]
@itwars - looks like go1.8rc2 was just released. My previous comment still applies, but this will get you the latest version of 1.8 (which is nice to test!)

```bash
$ go get golang.org/x/build/version/go1.8rc2
$ go1.8rc2 download
# make sure it was downloaded, then: 
$ go1.8rc2 get github.com/ponzu-cms/ponzu/...
``` 

then:

```bash
$ ponzu -gocmd=go1.8rc2 build
```

**Comment by nilslice** [comment]
Hi @itwars - 

I am going to assume you were able to fix this error and close this issue. If you have any other problems, please open another issue or reach out on Twitter to [@ponzu_cms](https://twitter.com/ponzu_cms).

Thanks!

**Comment by itwars** [comment]
Hi,

Sorry, yes close it! It works the way you show me :)

**Comment by udayn4** [comment]
Hi,

I went through your video and wanted to test it out. 
Go version : **go version go1.9.3 windows/amd64**

When I type  go get github.com/ponzu-cms/ponzu/..., the screen is just static. The cursor just stays there and nothing happens. 

Can you please help me out.

**Comment by nilslice** [comment]
@udayn4 - sorry about that. How long have you waited for the command to finish while the screen is static?

Try this command too:
`go get -u -v github.com/ponzu-cms/ponzu/... `

The `-v` will add verbose output so you should get more information about what is happening.
