### ISSUE TITLE
Main Field on Content

### ISSUE THREAD

**Issue by junnotantra** [ponzu-cms/ponzu#326]
Hi guys, 

I found myself always updating the `String()` method of every content I've made, to make the listing on admin dashboard readable and SEO friendly slug. Instead of `content: abcd-1234-xyz` we get `content: some pretty title here`

So I think it would be great to have this from the start, right after we generate the content. I've made a PR for this on #325 . Let me know what you guys think. :clinking_glasses:

**Comment by nilslice** [comment]
Hi @junnotantra - 

Could you post a screen shot of how the CLI operation works (when you create and assign this Main field) and the resulting screen shot of the Admin dashboard where the effect is applied? 

I _think_ I understand, but I'm not fully clear on what's happening. Thanks!!

**Comment by junnotantra** [comment]
Hi ollie,

> What happens if no field is defined as main via the asterisk prefix - what is the default behaviour when a content item is generated?

By default it's using UUID, like the current condition

> What is the procedure to change the main item once the content item is generated? In the go file itself. How would this be done?

This changes only modify the `String()` method. Instead of always using UUID, now the user can select which field to be used.
Nothing changed if user want to change it from the code. User can just edit it.

> What is the impact of content items pushed into Ponzu using the API, rather than the admin UI? Does the code patch cover both routes for data into Ponzu?

This only change the output of generated content file. Should have no impact on writing new content.

**Comment by junnotantra** [comment]
Hi @nilslice 

This is what we get with this command
```bash
ponzu gen content review *title:"string" body:"string":richtext rating:"int"
```

Content listing
![Screenshot from 2019-10-31 08-25-09](https://user-images.githubusercontent.com/6746159/67911186-49aadf00-fbb8-11e9-9c9e-37c35649883e.png)

Default slug
![Screenshot from 2019-10-31 08-25-21](https://user-images.githubusercontent.com/6746159/67911200-5596a100-fbb8-11e9-9e53-579228cc4f7a.png)

**Comment by olliephillips** [comment]
This all works for me. I think as an optional feature it's an intuitive and useful addition to the generate cli. Going to merge it. Thank you!
