### ISSUE TITLE
Hide content from admin

### ISSUE THREAD

**Issue by davidjije** [ponzu-cms/ponzu#336]
Hi,
via Ponzu CMS is it possible to hide content from admin but to leave API routes (get, create, update)?

**Comment by nilslice** [comment]
@davidjije - currently no. Just to make sure I understand your use case, you would want to define a set of admin users by their email to "reject" access to content types in the admin section?

**Comment by davidjije** [comment]
Nope. I just want that none of the admins could see content from Ponzu cms admin panel. I want to make content "visible" only by API routes.

**Comment by nilslice** [comment]
You can start the ponzu process in API-only mode.

Check the output of `ponzu -h` I believe, and look for the run or start command info.

**Comment by davidjije** [comment]
Sorry. I explained badly. Imagine I have 2 content types (x and y). I want `x` to be visible for admin in the panel and also from API routes. But I want to hide `y` content from admin and make visible only for API routes.

**Comment by nilslice** [comment]
I see -- no, that's not possible. Thanks for clarifying!

**Comment by davidjije** [comment]
Sad. Ok, Thank you
