### ISSUE TITLE
go module support

### ISSUE THREAD

**Issue by RPing** [ponzu-cms/ponzu#344]
Some dependency latest version enforced go module support, like `bleve`
https://github.com/blevesearch/bleve/issues/1373

So build ponzu, that is `GO111MODULE=off ponzu build`,
the following error occurs:
```
$ GO111MODULE=off ponzu build
../../blevesearch/bleve/index/scorch/segment_plugin.go:22:2: cannot find package "github.com/blevesearch/zap/v11" in any of:
	/usr/local/go/src/github.com/blevesearch/zap/v11 (from $GOROOT)
	/home/rpchen1228/go/src/github.com/blevesearch/zap/v11 (from $GOPATH)
Error: exit status 1
Usage:
  ponzu build [flags]

Examples:
$ ponzu build
(or)
$ ponzu build --gocmd=go1.8rc1

Flags:
  -h, --help   help for build

Global Flags:
      --gocmd string   custom go command if using beta or new release of Go (default "go")

exit status 1

```

**Comment by nilslice** [comment]
It would make a great PR :)

**Comment by dmitridb** [comment]
I don't really see this in the docs or anything but all I really had to do in order to get this up was vendoring the dependencies into what I was doing. So as follows, for an example:

git init
go mod init github.com/dmitridb/ponzu-example
go mod vendor
ponzu build

**Comment by olliephillips** [comment]
Edit : I just misread your comment, you are building the server.

@dmitridb That's a good shout but the dependency piece is more about how Ponzu builds the ponzu server binary internally I think. It's been historically dependent on GOPATH, and does not reference go.mod. I'm pretty sure that's the case. Bit rusty myself TBH.

**Comment by dmitridb** [comment]
Yeah they really fixed all of that in recent version of golang it's pretty nice tbh

**Comment by dmitridb** [comment]
People were using all sorts of insane stuff before like gopkg.in or whatever so it's nice that they unified things

**Comment by saeed-golshan** [comment]
I have this problem too when I do this:
`git init
go mod init github.com/dmitridb/ponzu-example
go mod vendor
ponzu build`
no content appeared when I make some content

**Comment by Avarsa** [comment]
> I have this problem too when I do this:
> `git init go mod init github.com/dmitridb/ponzu-example go mod vendor ponzu build`
> no content appeared when I make some content

Same. Unable to see any content here. What could be happening here?

**Comment by dmitridb** [comment]
lmfao this is such a dead project are you guys seriously paying attention to my shitty little github page

hahaha

ok pro tip check where i cloned this from and see that it was given up on a long time ago, this whole project has like structural issues with it basically, like you don't want to use it i just cloned it a long time ago thinking i might want to fix it but gave up when i realized people are paying me for my time in front of the computer and i have better shit to do than fix some crap on github i didn't write in the first place

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by olliephillips** [comment]
The project isn’t maintained anymore. Modules support isn’t there, and probably won’t ever be, unless someone forks the project and implements modules that’s where things are.
