### ISSUE TITLE
NOTICE: original author & maintainer is stepping away from the project

### ISSUE THREAD

**Issue by nilslice** [ponzu-cms/ponzu#349]
Hi folks -- I should have posted this a long time ago, but I've moved on from any maintenance of this project. 

The [Ponzu organization](https://github.com/ponzu-cms), all of its repositories, the [twitter account](https://twitter.com/ponzu_cms), and the domain name "ponzu-cms.org" have been acquired by [apilayer](https://apilayer.com). For all future support regarding licensing, bugs, feature requests, etc. please refer to their team. 

I will no longer be involved with this project. 

Best regards,
Steve

**Comment by nilslice** [comment]
In an attempt to inform folks who have open issues/PRs:

#348 @necokeine
#347 @ragouel
#344 @RPing
#342 @coldestheart
#341 @hadooping
#340 @yhyf
#339 @Loginsoft-Research
#338 @Loginsoft-Research
#337 @iceb0y
#334 @mangelajo
#331 @leelavg
#330 @nilslice
#329 @dhilst
#323 @ghost
#304 @ghost
#291 @nilslice
#279 @joshdstockdale
#273 @ghost
#263 @nanohard
#196 @aldsondiego 
#190 @nilslice 
#165 @nilslice 
#60 @paultyng
#335 @dhilst
#327 @junnotantra

**Comment by dmitridb** [comment]
Bruh I'm already like taking the good parts outta your codebase and flensing it. Tentative project name -- reducing it to 'mirin' hahahaha

**Comment by dmitridb** [comment]
Thanks for the inspiration!

**Comment by coldestheart** [comment]
Any way thanks for you work! From the first time I've started using ponzu I've made a huge step forward in golang learning and now writing own cms. Big thanks for help me understand(thanks for commented code and code purity) golang.

**Comment by nilslice** [comment]
@coldestheart - happy to know that Ponzu helped you. I hope to see your CMS someday & that yours can help others too!

**Comment by gedw99** [comment]
> Hi folks -- I should have posted this a long time ago, but I've moved on from any maintenance of this project.
> 
> The [Ponzu organization](https://github.com/ponzu-cms), all of its repositories, the [twitter account](https://twitter.com/ponzu_cms), and the domain name "ponzu-cms.org" have been acquired by [apilayer](https://apilayer.com). For all future support regarding licensing, bugs, feature requests, etc. please refer to their team.
> 
> I will no longer be involved with this project.
> 
> Best regards,
> Steve

So has the code moved ? Or I should fork if I want to e tend the cm/s? I am adding badger dB with subscriptions.

If I work on an issue / PR is someone going to merge it ?

**Comment by dmitridb** [comment]
yeah its done haha, gotta fork

theres a few security issues that need to be addressed you can find a bot found in the issues as well

i woulda gone all in on this myself but other work called

Sent from ProtonMail mobile

-------- Original Message --------
