### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by codlin** [ponzu-cms/ponzu#357]
It hasn't been updated for a year.

**Comment by m-arrieta-r** [comment]
I would say not :( because the last commit was almost two years ago.

**Comment by oz123** [comment]
I bumped into a fork which seemed active, but I can't find it ...

**Comment by oz123** [comment]
Seems a bit more active https://github.com/kudzu-cms/kudzu/releases/tag/v0.12.1
