### ISSUE TITLE
Features suggestions

### ISSUE THREAD

**Issue by roscopecoltran** [ponzu-cms/ponzu#49]
Hi,

Hope you are all well !

I am testing **ponzu cms** those days and made myself a couple of remarks about what could be awesome to have embedded in it.

It would be awesome to have:
- [Searchkit](https://github.com/searchkit/searchkit), for some advanced search features 
- [vue-admin](https://github.com/vue-bulma/vue-admin) for more backend oriented widgets
- [admin-on-rest](https://github.com/marmelab/admin-on-rest) a rest admin boilerplate for content browsing, editing and filtering
- An html ui composition interface, eg [lib-compose](https://github.com/tarent/lib-compose)

What is the current road-map for ponzu ? What are your goals with this framework ?

Cheers,
Richard

**Comment by gedw99** [comment]
Regarding Searchkit, there is the same functionality in golang by using bleve, which can use boltdb. All Content in the CMS can then be searchable, with full facet searching. 
I think this is much better than using elastic with Java dependencies.

https://github.com/blevesearch/bleve

**Comment by roscopecoltran** [comment]
I was thinking to bridge elasticsearch with a docker container through a docker-compose file for larger dataset to index and query; bleve won't work on a dataset with 10k+ records.

interesting projects using bleve:
- https://github.com/bobinette/papernet (bleve + boltdb)
- https://github.com/dorsha/lennon ( bleve and elastic)

Actually, I am giving a try to [qor-admin](https://github.com/qor/admin) and ponzu, as i d like to create an easy and quick web admin for a project like [limo](https://github.com/hoop33/limo) and maybe re-use this boilerplate for another project called [dim](https://github.com/nhurel/dim); both are using bleve as a full-text search engine.

**Comment by gedw99** [comment]
I think your mistaken about how large a dataset bleve can handle. i have used bleve on huge datasets. It support alias and so can be run on clusters of servers.
Couchbase wrote it and integrated bleve into their full text search.
https://blog.couchbase.com/2016/february/couchbase-4.5-developer-preview-couchbase-fts?facet=blog%2Fblogs.facets%2FAuthor%2FLaurent+Doguin%2FYear%2F2016%2FTags%2Fbleve

i have done 3 projects with bleve and its been solid as a rock. We were indexing 4 Petabytes through it a year ago with alias shards. 

Its very easy to make full text searching & faceted searching with bleve on any content.
i think doing projects like limo and dim would be a good match for bleve.

Also the developer behind bleve (Marty) is awesome and very approachable.

**Comment by nilslice** [comment]
Hi @roscopecoltran - 

Thank you for your feedback and suggestions - it's great to see other people enjoying Ponzu and sharing ideas about how to make it better.

Regarding your suggestions:

**Comment by nilslice** [comment]
@gedw99 - first, nice profile picture. PF is the best. I've played guitar for the majority of my life and David Gilmour is just incredible.

If you have suggestions as to how we could implement Bleve into our search system (or replace it), I would be grateful to hear them. Currently there is only a search handler inside the admin UI to do exact word/phrase matching on the JSON documents in Bolt. The purpose is solely to help admins find content they have added.

I think that Bleve could support a really nice API endpoint for external search requests by outside users.. but I haven't used it and would need to make sure we can prevent indexing of the Bolt buckets that hold sensitive information, and the ones which are hidden as per a Ponzu developers implementation of the `item.Hideable` interface which prevents content types from being exposed through the content API.

Another consideration would be how Bleve would work with other DB backends. There has been some talk about providing support for other common databases like Postgres & MySQL. Although adding swappable DB backends is probably fairly distant, its good to think about it now when possibly adding more DB-related features.

**Comment by gedw99** [comment]
Am on mobile..

It's maybe 50 lines of code.

Each content interface needs to only implement a bleve mapper. It can
handle numeric and time ranges too.

Then on search there is a standard bleve interface.
You probably want a global search that can display a GUI with a few etc for
each content item.

You can use aliases to ensure it does not clash with other boltdb buckets.

Also have a look at storm boltdb in github.
Might help everything else

That would do it.

I can write more when not on mobile with some links !!

**Comment by gedw99** [comment]
I wil now open a new issue just for the bleve stuff. This issue has too many things in it.

**Comment by roscopecoltran** [comment]
@gedw99 I looked at bleve, 1/2 year ago and asked the author about the index scalability of bleve, he did not told me such number (much more 200k). 

In one word, that would be awesome :-) I know that **couchbase** is doing some great things, for eg they did a couple of cool things for distributed deep learning like [elastic-thoughts](https://github.com/tleyden/elastic-thought).

I will take a couple of hours to read the article and make some tests.

I saw the following interesting project:
- https://github.com/couchbase/cbft 

Cheers,
Richard

**Comment by gedw99** [comment]
Checked the new issue I created.

Should help slot.

**Comment by nilslice** [comment]
I need to familiarize myself with Bleve and check out storm. Will report back on #51. Thank you!

**Comment by gedw99** [comment]
I am curious myself because the design of Ponzi looks pretty awesome. It's
really similar to something I started to build, but now I am getting on
board with adding some of my ideas to ponzu. I will raise them as feature
discussion / issues if that's ok. See what you think...

The technical aspects are pretty easy thanks to the work and maturity that
Marty has put into bleve

**Comment by nilslice** [comment]
Thank you, I would be very happy to have contributions and get more people involved. I think the design already lends itself well to the approach you mentioned where Content items implement a mapper interface. 

If you look at the 'system/item' package, you'll see a number of other interfaces that are exported and that Item implements by default (most as no-ops, which the intention of them being overrriden). 

Do you think we could extend Item to implement a default mapping interface so the Ponzu developer wouldn't need to do this themselves in their content file?

**Comment by gedw99** [comment]
Yes I think you can use a default mapping. That's exactly what I was also
thinking.
Hence, This is why I mentioned that you should start offering types such as
numeric range and datatime Range as first class types in the core of ponzu.
These are needed for bleve in more complex search cases which you will hit.
The common GUI widgets can then be fully aware of these first class types
as well as bleve.
I think it closes off lots of potential bugs too.

Here is another example of similar thinking. Might be good idea.
I was working on a CMSish system that runs on mobiles and did code gen too.
The CMS was running on mobiles and desktops and web and each user had a
offline database using boltdb.. I offered 3 first class types that I
generated from that all related to data synchronisation.
1. String
2. Walstring. This is a write ahead log style string that is used for
Google hangouts / chat style of data sync.  When it syncs between users
databases it just has to enforce everything being an addition.
3. Docstring this was for real time and partitioned time document sync. For
example Google documents  where the users want to collaborate on a document
for editting.

The sync system then knew what do do based on these archetypes ( a better
word for this ). The generic admin GUI also knew what to do to display
controls.

As a result a user can create complex compositions if these archetypes.
For example a User has many books.
Books is just a list
Book content is make up of a docstring, cover image, etc.

Mozilla has a nice golang library that does this sync btw. Its uses for the
Firefox sync of tabs, bookmarks , etc. It is very simple and self contained
like your ponzu is.
If you want I can write all this sync stuff up as a issue idea. I might get
time to help on it but am on holidays right now. So no computer work for me
for a month.

**Comment by nilslice** [comment]
@roscopecoltran - since it seems like the Bleve / full text search is the most interesting to us on this thread, I am going to close out this issue and we can carry out the conversation on #51.

If you would like to discuss the other ideas you suggested, please read my responses and we can chat in Gopher Slack on the ponzu channel (join here: https://invite.slack.golangbridge.org/)

Thanks!
