### ISSUE TITLE
Help with ponzu as daemon

### ISSUE THREAD

**Issue by axenovV** [ponzu-cms/ponzu#52]
Hello, I added ponzu-server in upstart, but I start ponzu-server  have some error. 

```
sudo service ponzu-server start
Job for ponzu-server.service failed because the control process exited with error code. See "systemctl status ponzu-server.service" and "journalctl -xe" for details.
```
journalctl -xe:
```
Jan 28 19:12:22 cs67724 systemd[1]: ponzu-server.service: Unit entered failed state.
Jan 28 19:12:22 cs67724 systemd[1]: ponzu-server.service: Failed with result 'exit-code'.
Jan 28 19:12:22 cs67724 sudo[1069]: pam_unix(sudo:session): session closed for user root
Jan 28 19:12:30 cs67724 sudo[1095]:    ponzu : TTY=pts/0 ; PWD=/home/ponzu/work ; USER=root ; COMMAND=/bin/journalctl -xe
Jan 28 19:12:30 cs67724 sudo[1095]: pam_unix(sudo:session): session opened for user root by ponzu(uid=0)
Jan 28 19:13:14 cs67724 sudo[1095]: pam_unix(sudo:session): session closed for user root
Jan 28 19:16:58 cs67724 sudo[1118]:    ponzu : TTY=pts/0 ; PWD=/home/ponzu/work/src/remoteConfig/deployment/sysv ; USER=root ; COMM
Jan 28 19:16:58 cs67724 sudo[1118]: pam_unix(sudo:session): session opened for user root by ponzu(uid=0)
```

**Comment by nilslice** [comment]
Hi - what OS are you using? Could you share your init script? Admittedly, this is not an area in which I have much expertise but will try to see if I can help.

**Comment by axenovV** [comment]
@nilslice  Ubuntu 16.04, this is my init script: https://github.com/ponzu-cms/ponzu/blob/master/deployment/sysv/ponzu-server

As I understand it to use it as a daemon, the same script is in my project directory, which has been generated with ponzu gen

**Comment by nilslice** [comment]
I'm on mobile at the moment, and would otherwise try to find a resource to share with you.. I've only used this with init.d (sysv), but I believe it is compatible with Upstart. Maybe google something like "init.d script usage with upstart"?

**Comment by nilslice** [comment]
In the script I have provided, did you assign the $VARIABLES in the script to use your project info?

**Comment by axenovV** [comment]
@nilslice I've solved the problem, I do not have the variables in the script. Thanks

**Comment by nilslice** [comment]
Ok, great. If you are able to share, I'd love to see what to made!

**Comment by axenovV** [comment]
```
PROJECT_DIR=/home/ponzu/work/src/remoteConfig
SCRIPT="cd $PROJECT_DIR && /home/ponzu/work/bin/ponzu --port=8080 run"
RUNAS=ponzu

PIDFILE=/home/ponzu/run/ponzu-server.pid
LOGFILE=/home/ponzu/log/ponzu-server.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f ponzu-server remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
```

**Comment by nilslice** [comment]
Hah sorry, I meant the project you made with Ponzu. But the script looks right!

**Comment by axenovV** [comment]
@nilslice  Yes. Can I somehow disable caching? I'll update an object, but the field had not changed.

<img width="560" alt="2017-01-29 0 58 33" src="https://cloud.githubusercontent.com/assets/9257530/22400134/17bf50e2-e5be-11e6-8035-3579c6d59379.png">
 And this is my response from api:
<img width="204" alt="2017-01-29 0 58 52" src="https://cloud.githubusercontent.com/assets/9257530/22400139/24be4280-e5be-11e6-855d-44edf1840be0.png">

<img width="656" alt="2017-01-29 0 59 25" src="https://cloud.githubusercontent.com/assets/9257530/22400143/3704970a-e5be-11e6-903b-49ee8a25392b.png">

When I put chec kmark , and save the settings, the check mark is still uncheked :(

**Comment by axenovV** [comment]
@nilslice Yes, I use ponzu as simple api for mobile app

**Comment by nilslice** [comment]
Hm. There should be a new Etag generated when you update content in the CMS which invalidates cache automatically. 

The check mark never stays checked, as it is just a indicator that you want to manually invalidate the cache when you click the Save button on that page. 

Have you tried doing a hard refresh in the browser? It should have updated when you changed the content, but it will help to know if you've hard refreshed the browser yet.

**Comment by axenovV** [comment]
@nilslice I've solved problem with cache :) thanks)

**Comment by nilslice** [comment]
You bet. Glad you fixed it
