### ISSUE TITLE
Error after upgrading to 0.8.2

### ISSUE THREAD

**Issue by bketelsen** [ponzu-cms/ponzu#58]
I'll dig into this myself, but wanted to post this stack trace here too:

2017/01/31 19:44:10 http: panic serving 127.0.0.1:52350: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc4201270e0)
	/root/sdk/go1.8rc2/src/net/http/server.go:1721 +0xd0
panic(0x88e400, 0xb6af10)
	/root/sdk/go1.8rc2/src/runtime/panic.go:489 +0x2cf
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.gzipResponseWriter.Push(0xb39a40, 0xc420116380, 0x0, 0x0, 0xc420ddf290, 0xc420e19f60, 0x1d, 0xc420e19f80, 0xc420e19f60, 0x1d)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/handlers.go:371 +0x76
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.(*gzipResponseWriter).Push(0xc420017c80, 0xc420e19f60, 0x1d, 0x0, 0x11, 0xc420e19f60)
	<autogenerated>:6 +0x87
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.push.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3, 0xc420e19f01, 0x18, ...)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/push.go:26 +0xf7
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/tidwall/gjson.Result.ForEach(0x5, 0xc420e19f00, 0x1a, 0x0, 0x0, 0x0, 0xf6, 0xc420047930)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/tidwall/gjson/gjson.go:219 +0x34d
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.push(0xb39bc0, 0xc420017c80, 0xc42000b900, 0x931628, 0xc4200f7d40, 0x111, 0x111)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/push.go:32 +0x1ee
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.contentHandler(0xb39bc0, 0xc420017c80, 0xc42000b900)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/handlers.go:132 +0x248
net/http.HandlerFunc.ServeHTTP(0x9316f0, 0xb39bc0, 0xc420017c80, 0xc42000b900)
	/root/sdk/go1.8rc2/src/net/http/server.go:1942 +0x44
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.Gzip.func1(0xb39a40, 0xc420116380, 0xc42000b900)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/handlers.go:342 +0x2d5
net/http.HandlerFunc.ServeHTTP(0xc42011aa20, 0xb39a40, 0xc420116380, 0xc42000b900)
	/root/sdk/go1.8rc2/src/net/http/server.go:1942 +0x44
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.CORS.func1(0xb39a40, 0xc420116380, 0xc42000b900)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/handlers.go:310 +0x9c
net/http.HandlerFunc.ServeHTTP(0xc42011aa30, 0xb39a40, 0xc420116380, 0xc42000b900)
	/root/sdk/go1.8rc2/src/net/http/server.go:1942 +0x44
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/db.CacheControl.func1(0xb39a40, 0xc420116380, 0xc42000b900)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/db/cache.go:26 +0x247
net/http.HandlerFunc.ServeHTTP(0xc42011d400, 0xb39a40, 0xc420116380, 0xc42000b900)
	/root/sdk/go1.8rc2/src/net/http/server.go:1942 +0x44
github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api.Record.func1(0xb39a40, 0xc420116380, 0xc42000b900)
	/root/go/src/github.com/gopheracademy/material/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/handlers.go:319 +0x74
net/http.HandlerFunc.ServeHTTP(0xc42011aa40, 0xb39a40, 0xc420116380, 0xc42000b900)
	/root/sdk/go1.8rc2/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xb795a0, 0xb39a40, 0xc420116380, 0xc42000b900)
	/root/sdk/go1.8rc2/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420148160, 0xb39a40, 0xc420116380, 0xc42000b900)
	/root/sdk/go1.8rc2/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201270e0, 0xb3a340, 0xc420118f80)
	/root/sdk/go1.8rc2/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/root/sdk/go1.8rc2/src/net/http/server.go:2668 +0x2ce

**Comment by bketelsen** [comment]
Resolved by disabling gzip.

**Comment by nilslice** [comment]
Could I see your Push method code and the struct + fields it's on?

**Comment by bketelsen** [comment]
have no push method :)

**Comment by nilslice** [comment]
Spooky!

Ok I'm at the gym but will run tests when I'm home later. Lmk if you have any questions while debugging - I should be able to answer.

**Comment by nilslice** [comment]
@bketelsen - did you make any headway on this? I have tried to reproduce using numerous variations of references, push/no-push, http/https, and can't seem to get this same panic.
