### ISSUE TITLE
Sluggable

### ISSUE THREAD

**Issue by olliephillips** [ponzu-cms/ponzu#80]
I'm not clear whether items should be accessible by slug (sluggable) by default. The interface methods seem to be about overriding the default slug should there be conflicts.  

This request to the API (with a valid slug), gives me a blank page and `400 Bad Request` error:

```
GET http://localhost:8080/api/contents?slug=item-id-50b1fcdd-87b1-4e4a-a9a5-5ca6d61a43cd
```

What am I doing wrong here?

**Comment by nilslice** [comment]
Hi -

Sluggable content should be requested using the /api/content path with the
slug query param you're using.

There are both "content" (singular) and "contents" (plural) endpoints -
sorry that they are not more different in name from one another, or well
documented for that matter.

Let me know if that fixes it.

Steve

**Comment by olliephillips** [comment]
It does. And it's there in the Wiki now I look again - similar as you say - but I should have read it properly!
